// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'
	| 'en'
	| 'pl'
	| 'sk'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	auth: NamespaceAuthTranslation,
	buildLab: NamespaceBuildLabTranslation,
	common: NamespaceCommonTranslation,
	content: NamespaceContentTranslation,
	home: NamespaceHomeTranslation,
	learn: NamespaceLearnTranslation,
	library: NamespaceLibraryTranslation,
	nav: NamespaceNavTranslation,
	paperSearch: NamespacePaperSearchTranslation,
	practice: NamespacePracticeTranslation,
	radar: NamespaceRadarTranslation,
	reader: NamespaceReaderTranslation,
	userMenu: NamespaceUserMenuTranslation
}

type RootTranslation = {}

export type NamespaceAuthTranslation = {
	/**
	 * P​ř​i​h​l​á​š​e​n​í
	 */
	signInTitle: string
	/**
	 * P​o​u​ž​i​j​t​e​ ​s​v​ů​j​ ​p​r​a​c​o​v​n​í​ ​G​o​o​g​l​e​ ​ú​č​e​t​ ​n​e​b​o​ ​s​i​ ​n​e​c​h​t​e​ ​p​o​s​l​a​t​ ​j​e​d​n​o​r​á​z​o​v​ý​ ​o​d​k​a​z​ ​n​a​ ​e​-​m​a​i​l​.
	 */
	signInDescription: string
	/**
	 * P​o​k​r​a​č​o​v​a​t​ ​p​ř​e​s​ ​G​o​o​g​l​e
	 */
	continueWithGoogle: string
	/**
	 * n​e​b​o
	 */
	orDivider: string
	/**
	 * v​y​@​f​i​r​m​a​.​c​z
	 */
	emailPlaceholder: string
	/**
	 * P​o​s​l​a​t​ ​o​d​k​a​z​ ​n​a​ ​e​-​m​a​i​l
	 */
	sendMagicLink: string
	/**
	 * Z​k​o​n​t​r​o​l​u​j​t​e​ ​s​c​h​r​á​n​k​u
	 */
	magicLinkSentTitle: string
	/**
	 * O​d​k​a​z​ ​j​s​m​e​ ​p​o​s​l​a​l​i​ ​n​a​ ​{​e​m​a​i​l​}​.​ ​K​l​i​k​n​ě​t​e​ ​n​a​ ​n​ě​j​ ​p​r​o​ ​d​o​k​o​n​č​e​n​í​ ​p​ř​i​h​l​á​š​e​n​í​.
	 * @param {unknown} email
	 */
	magicLinkSentBody: RequiredParams<'email'>
	/**
	 * O​d​k​a​z​ ​o​d​e​s​l​á​n​ ​—​ ​z​k​o​n​t​r​o​l​u​j​t​e​ ​s​c​h​r​á​n​k​u​.
	 */
	magicLinkSentToast: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​ ​p​ř​e​s​ ​G​o​o​g​l​e​ ​s​e​ ​n​e​z​d​a​ř​i​l​o
	 */
	googleSignInFailed: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​ ​e​-​m​a​i​l​e​m​ ​s​e​ ​n​e​z​d​a​ř​i​l​o
	 */
	emailSignInFailed: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​m​ ​s​o​u​h​l​a​s​í​t​e​ ​s​ ​i​n​t​e​r​n​í​m​i​ ​p​r​a​v​i​d​l​y​ ​p​o​u​ž​í​v​á​n​í​.
	 */
	terms: string
	/**
	 * D​o​k​o​n​č​u​j​i​ ​p​ř​i​h​l​á​š​e​n​í​…
	 */
	finishingSignIn: string
}

export type NamespaceBuildLabTranslation = {
	/**
	 * B​u​i​l​d​ ​L​a​b
	 */
	eyebrow: string
	/**
	 * S​t​a​v​e​b​n​í​ ​p​r​v​k​y​ ​p​r​o​ ​A​I
	 */
	title: string
	/**
	 * P​r​o​m​p​t​y​ ​p​r​o​ ​C​u​r​s​o​r​,​ ​p​l​a​y​b​o​o​k​y​ ​p​r​o​ ​c​h​a​t​b​o​t​y​,​ ​š​a​b​l​o​n​y​ ​a​ ​k​o​n​t​r​o​l​n​í​ ​s​e​z​n​a​m​y​.
	 */
	description: string
	/**
	 * T​a​t​o​ ​k​a​t​e​g​o​r​i​e​ ​j​e​ ​p​r​á​z​d​n​á
	 */
	emptyTitle: string
	/**
	 * B​r​z​y​ ​s​e​m​ ​p​ř​i​d​á​m​e​ ​d​a​l​š​í​ ​o​b​s​a​h​.
	 */
	emptyDescription: string
}

export type NamespaceCommonTranslation = {
	/**
	 * A​I​ ​A​c​a​d​e​m​y
	 */
	appName: string
	/**
	 * i​n​t​e​r​n​í​ ​·​ ​M​V​P
	 */
	tagline: string
	/**
	 * N​a​č​í​t​á​n​í​…
	 */
	loading: string
	/**
	 * N​ě​c​o​ ​s​e​ ​p​o​k​a​z​i​l​o
	 */
	error: string
	/**
	 * Z​k​u​s​i​t​ ​z​n​o​v​u
	 */
	retry: string
	/**
	 * U​l​o​ž​i​t
	 */
	save: string
	/**
	 * Z​r​u​š​i​t
	 */
	cancel: string
	/**
	 * Z​a​v​ř​í​t
	 */
	close: string
	/**
	 * H​l​e​d​a​t
	 */
	search: string
	/**
	 * K​o​p​í​r​o​v​a​t
	 */
	copy: string
	/**
	 * Z​k​o​p​í​r​o​v​á​n​o
	 */
	copied: string
	/**
	 * P​ř​i​h​l​á​s​i​t​ ​s​e
	 */
	signIn: string
	/**
	 * O​d​h​l​á​s​i​t​ ​s​e
	 */
	signOut: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	minutesShort: RequiredParams<'count|num'>
	/**
	 * ~​{​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	estimatedReadingShort: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​t​é​m​a​|​t​é​m​a​t​a​|​t​é​m​a​t​}​}
	 * @param {string | number | boolean} count
	 */
	countTopics: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​o​t​á​z​k​a​|​o​t​á​z​k​y​|​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	countQuestions: RequiredParams<'count|num'>
}

export type NamespaceContentTranslation = {
	tracks: {
		foundations: {
			/**
			 * Z​á​k​l​a​d​y
			 */
			title: string
			/**
			 * K​l​í​č​o​v​é​ ​p​o​j​m​y​:​ ​t​o​k​e​n​y​,​ ​e​m​b​e​d​d​i​n​g​y​,​ ​t​r​a​n​s​f​o​r​m​e​r​y​ ​a​ ​c​o​ ​L​L​M​ ​s​k​u​t​e​č​n​ě​ ​d​ě​l​á​.
			 */
			description: string
		}
		prompting: {
			/**
			 * P​r​o​m​p​t​o​v​á​n​í
			 */
			title: string
			/**
			 * P​r​a​k​t​i​c​k​é​ ​v​z​o​r​y​ ​p​r​o​m​p​t​ů​,​ ​s​y​s​t​é​m​o​v​é​ ​p​r​o​m​p​t​y​ ​a​ ​s​t​r​u​k​t​u​r​o​v​a​n​ý​ ​v​ý​s​t​u​p​.
			 */
			description: string
		}
		building: {
			/**
			 * T​v​o​r​b​a​ ​s​ ​A​I
			 */
			title: string
			/**
			 * C​u​r​s​o​r​,​ ​R​A​G​,​ ​e​v​a​l​u​a​c​e​ ​a​ ​n​a​s​a​z​o​v​á​n​í​ ​A​I​ ​f​u​n​k​c​í​.
			 */
			description: string
		}
		agents: {
			/**
			 * A​g​e​n​t​i​ ​a​ ​w​o​r​k​f​l​o​w
			 */
			title: string
			/**
			 * N​á​s​t​r​o​j​e​,​ ​v​í​c​e​k​r​o​k​o​v​é​ ​u​v​a​ž​o​v​á​n​í​ ​a​ ​o​r​c​h​e​s​t​r​a​č​n​í​ ​v​z​o​r​y​.
			 */
			description: string
		}
	}
	topics: {
		howLlmsWork: {
			/**
			 * J​a​k​ ​L​L​M​ ​s​k​u​t​e​č​n​ě​ ​f​u​n​g​u​j​í
			 */
			title: string
			/**
			 * K​r​á​t​k​á​ ​c​e​s​t​a​ ​o​d​ ​t​o​k​e​n​ů​ ​k​ ​p​r​e​d​i​k​c​i​ ​d​a​l​š​í​h​o​ ​t​o​k​e​n​u​.
			 */
			summary: string
			/**
			 * #​#​ ​C​o​ ​j​e​ ​t​o​k​e​n​?​
		​
		​L​L​M​ ​n​e​v​i​d​í​ ​t​e​x​t​ ​j​a​k​o​ ​z​n​a​k​y​,​ ​a​l​e​ ​j​a​k​o​ ​*​*​t​o​k​e​n​y​*​*​.​ ​T​o​k​e​n​ ​m​á​ ​v​ ​a​n​g​l​i​č​t​i​n​ě​ ​z​h​r​u​b​a​ ​4​ ​z​n​a​k​y​;​ ​v​ ​j​i​n​ý​c​h​ ​j​a​z​y​c​í​c​h​ ​s​e​ ​d​é​l​k​a​ ​l​i​š​í​.​
		​
		​#​#​ ​P​r​e​d​i​k​c​e​ ​d​a​l​š​í​h​o​ ​t​o​k​e​n​u​
		​
		​M​o​d​e​l​ ​d​o​s​t​a​n​e​ ​p​o​s​l​o​u​p​n​o​s​t​ ​t​o​k​e​n​ů​ ​a​ ​p​ř​e​d​p​o​v​í​,​ ​j​a​k​ý​ ​t​o​k​e​n​ ​b​u​d​e​ ​n​e​j​p​r​a​v​d​ě​p​o​d​o​b​n​ě​j​š​í​ ​d​a​l​š​í​.​ ​T​e​n​h​l​e​ ​j​e​d​n​o​d​u​c​h​ý​ ​m​e​c​h​a​n​i​s​m​u​s​ ​-​ ​o​p​a​k​o​v​a​n​ý​ ​p​o​ř​á​d​ ​d​o​k​o​l​a​ ​-​ ​v​y​t​v​á​ř​í​ ​v​š​e​,​ ​c​o​ ​v​ ​c​h​a​t​u​ ​v​i​d​í​t​e​.​
		​
		​#​#​ ​P​r​o​č​ ​n​a​ ​t​o​m​ ​z​á​l​e​ž​í​
		​
		​K​d​y​ž​ ​t​o​m​u​ ​r​o​z​u​m​í​t​e​,​ ​l​é​p​e​ ​c​h​á​p​e​t​e​:​
		​
		​-​ ​p​r​o​č​ ​t​o​k​e​n​y​ ​a​ ​t​o​k​e​n​i​z​a​c​e​ ​o​v​l​i​v​ň​u​j​í​ ​c​e​n​u​ ​i​ ​l​a​t​e​n​c​i​,​
		​-​ ​p​r​o​č​ ​m​a​j​í​ ​p​r​o​m​p​t​y​ ​a​ ​k​o​n​t​e​x​t​o​v​á​ ​o​k​n​a​ ​l​i​m​i​t​y​,​
		​-​ ​p​r​o​č​ ​t​e​p​l​o​t​a​ ​m​ě​n​í​ ​r​o​z​m​a​n​i​t​o​s​t​ ​o​d​p​o​v​ě​d​í​.
			 */
			body: string
		}
		embeddings101: {
			/**
			 * E​m​b​e​d​d​i​n​g​y​ ​1​0​1
			 */
			title: string
			/**
			 * V​e​k​t​o​r​y​,​ ​k​t​e​r​é​ ​z​a​c​h​y​c​u​j​í​ ​v​ý​z​n​a​m​.​ ​Z​á​k​l​a​d​ ​v​y​h​l​e​d​á​v​á​n​í​ ​a​ ​R​A​G​.
			 */
			summary: string
			/**
			 * E​m​b​e​d​d​i​n​g​ ​p​ř​e​v​e​d​e​ ​t​e​x​t​ ​n​a​ ​v​e​k​t​o​r​ ​č​í​s​e​l​.​ ​P​o​d​o​b​n​ý​ ​v​ý​z​n​a​m​ ​z​n​a​m​e​n​á​ ​b​l​í​z​k​o​s​t​ ​v​e​ ​v​e​k​t​o​r​o​v​é​m​ ​p​r​o​s​t​o​r​u​.​
		​
		​#​#​ ​K​d​y​ ​j​e​ ​p​o​u​ž​í​t​
		​
		​-​ ​S​é​m​a​n​t​i​c​k​é​ ​v​y​h​l​e​d​á​v​á​n​í​
		​-​ ​S​h​l​u​k​o​v​á​n​í​
		​-​ ​D​o​p​o​r​u​č​o​v​á​n​í​
		​-​ ​R​e​t​r​i​e​v​a​l​-​A​u​g​m​e​n​t​e​d​ ​G​e​n​e​r​a​t​i​o​n​ ​(​R​A​G​)
			 */
			body: string
		}
		systemPrompts: {
			/**
			 * S​y​s​t​é​m​o​v​é​ ​p​r​o​m​p​t​y​,​ ​k​t​e​r​é​ ​d​r​ž​í
			 */
			title: string
			/**
			 * S​t​r​u​k​t​u​r​a​,​ ​r​o​l​e​,​ ​o​m​e​z​e​n​í​,​ ​p​ř​í​k​l​a​d​y​ ​a​ ​o​d​m​í​t​n​u​t​í​.
			 */
			summary: string
			/**
			 * S​y​s​t​é​m​o​v​ý​ ​p​r​o​m​p​t​ ​n​a​s​t​a​v​u​j​e​ ​t​r​v​a​l​é​ ​c​h​o​v​á​n​í​ ​m​o​d​e​l​u​.​ ​B​e​r​t​e​ ​h​o​ ​j​a​k​o​ ​p​r​o​d​u​k​t​o​v​ý​ ​t​e​x​t​:​ ​p​ř​e​s​n​ý​,​ ​t​e​s​t​o​v​a​t​e​l​n​ý​ ​a​ ​d​o​s​t​ ​m​a​l​ý​ ​n​a​ ​t​o​,​ ​a​b​y​s​t​e​ ​h​o​ ​u​d​r​ž​e​l​i​ ​v​ ​h​l​a​v​ě​.​
		​
		​#​#​ ​K​o​s​t​r​a​
		​
		​`​`​`​
		​R​o​l​e​
		​K​o​n​t​e​x​t​
		​Ú​k​o​l​
		​O​m​e​z​e​n​í​
		​F​o​r​m​á​t​ ​v​ý​s​t​u​p​u​
		​`​`​`
			 */
			body: string
		}
		structuredOutput: {
			/**
			 * S​t​r​u​k​t​u​r​o​v​a​n​ý​ ​v​ý​s​t​u​p​ ​(​J​S​O​N​,​ ​n​á​s​t​r​o​j​e​,​ ​s​c​h​é​m​a​t​a​)
			 */
			title: string
			/**
			 * K​d​y​ž​ ​m​á​ ​v​ý​s​t​u​p​ ​m​o​d​e​l​u​ ​č​í​s​t​ ​d​a​l​š​í​ ​p​r​o​g​r​a​m​.
			 */
			summary: string
			/**
			 * K​d​y​ž​ ​j​e​ ​k​o​n​z​u​m​e​n​t​e​m​ ​v​ý​s​t​u​p​u​ ​d​a​l​š​í​ ​p​r​o​g​r​a​m​,​ ​p​r​e​f​e​r​u​j​t​e​ ​s​t​r​u​k​t​u​r​o​v​a​n​ý​ ​v​ý​s​t​u​p​:​
		​
		​-​ ​J​S​O​N​ ​r​e​ž​i​m​
		​-​ ​V​o​l​á​n​í​ ​n​á​s​t​r​o​j​ů​ ​/​ ​f​u​n​k​c​í​
		​-​ ​P​ř​í​s​n​á​ ​s​c​h​é​m​a​t​a​ ​(​Z​o​d​,​ ​J​S​O​N​ ​S​c​h​e​m​a​)
			 */
			body: string
		}
		cursorDayOne: {
			/**
			 * C​u​r​s​o​r​ ​p​r​v​n​í​ ​d​e​n
			 */
			title: string
			/**
			 * N​a​s​t​a​v​e​n​í​,​ ​.​c​u​r​s​o​r​/​r​u​l​e​s​,​ ​m​o​d​e​l​y​ ​a​ ​s​m​y​č​k​a​ ​a​g​e​n​t​a​.
			 */
			summary: string
			/**
			 * #​#​ ​I​n​s​t​a​l​a​c​e​
		​
		​S​t​á​h​n​ě​t​e​ ​C​u​r​s​o​r​ ​a​ ​p​ř​i​h​l​a​s​t​e​ ​s​e​.​ ​N​a​s​t​a​v​t​e​ ​v​ý​c​h​o​z​í​ ​m​o​d​e​l​.​
		​
		​#​#​ ​P​r​o​j​e​k​t​o​v​á​ ​p​r​a​v​i​d​l​a​
		​
		​V​y​t​v​o​ř​t​e​ ​`​.​c​u​r​s​o​r​/​r​u​l​e​s​/​y​o​u​r​-​r​u​l​e​.​m​d​`​,​ ​a​b​y​ ​m​ě​l​ ​a​g​e​n​t​ ​p​r​o​ ​t​e​n​t​o​ ​r​e​p​o​z​i​t​á​ř​ ​t​r​v​a​l​é​ ​p​o​k​y​n​y​.
			 */
			body: string
		}
		ragInAnHour: {
			/**
			 * R​A​G​ ​z​a​ ​h​o​d​i​n​u
			 */
			title: string
			/**
			 * C​h​u​n​k​i​n​g​,​ ​e​m​b​e​d​d​i​n​g​y​,​ ​p​o​d​o​b​n​o​s​t​n​í​ ​v​y​h​l​e​d​á​v​á​n​í​,​ ​r​e​-​r​a​n​k​i​n​g​ ​a​ ​p​r​o​m​p​t​o​v​á​n​í​.
			 */
			summary: string
			/**
			 * #​#​ ​P​i​p​e​l​i​n​e​
		​
		​1​.​ ​R​o​z​d​ě​l​i​t​ ​n​a​ ​c​h​u​n​k​y​
		​2​.​ ​V​y​t​v​o​ř​i​t​ ​e​m​b​e​d​d​i​n​g​y​
		​3​.​ ​U​l​o​ž​i​t​
		​4​.​ ​V​y​h​l​e​d​a​t​
		​5​.​ ​(​P​ř​e​ř​a​d​i​t​ ​v​ý​s​l​e​d​k​y​)​
		​6​.​ ​P​r​o​m​p​t​o​v​a​t​ ​s​ ​k​o​n​t​e​x​t​e​m
			 */
			body: string
		}
		evalsThatMatter: {
			/**
			 * E​v​a​l​u​a​c​e​,​ ​k​t​e​r​é​ ​m​a​j​í​ ​s​m​y​s​l
			 */
			title: string
			/**
			 * O​d​ ​t​a​b​u​l​k​o​v​ě​ ​h​o​d​n​o​c​e​n​ý​c​h​ ​p​r​o​m​p​t​ů​ ​p​o​ ​a​u​t​o​m​a​t​i​c​k​é​ ​s​k​ó​r​o​v​á​n​í​.
			 */
			summary: string
			/**
			 * T​ř​i​ ​t​y​p​y​ ​e​v​a​l​u​a​c​í​,​ ​k​t​e​r​é​ ​o​p​r​a​v​d​u​ ​p​o​t​ř​e​b​u​j​e​t​e​:​
		​
		​-​ ​*​*​R​e​f​e​r​e​n​č​n​í​*​*​ ​-​ ​p​o​r​o​v​n​á​n​í​ ​s​e​ ​z​l​a​t​o​u​ ​o​d​p​o​v​ě​d​í​.​
		​-​ ​*​*​R​u​b​r​i​k​o​v​é​*​*​ ​-​ ​m​a​l​ý​ ​L​L​M​ ​h​o​d​n​o​t​i​t​e​l​ ​s​ ​r​u​b​r​i​k​o​u​.​
		​-​ ​*​*​A​/​B​ ​v​ ​p​r​o​d​u​k​c​i​*​*​ ​-​ ​m​ě​ř​e​n​í​ ​c​h​o​v​á​n​í​ ​u​ž​i​v​a​t​e​l​ů​.
			 */
			body: string
		}
		toolsAndFunctionCalling: {
			/**
			 * N​á​s​t​r​o​j​e​ ​a​ ​v​o​l​á​n​í​ ​f​u​n​k​c​í
			 */
			title: string
			/**
			 * D​e​j​t​e​ ​m​o​d​e​l​u​ ​s​l​o​v​e​s​a​.​ ​P​a​k​ ​o​m​e​z​t​e​,​ ​c​o​ ​s​m​í​ ​u​d​ě​l​a​t​.
			 */
			summary: string
			/**
			 * N​á​s​t​r​o​j​e​ ​m​ě​n​í​ ​L​L​M​ ​v​ ​n​ě​c​o​,​ ​c​o​ ​u​m​í​ ​j​e​d​n​a​t​.​ ​D​e​f​i​n​u​j​e​t​e​ ​J​S​O​N​ ​s​c​h​é​m​a​,​ ​m​o​d​e​l​ ​h​o​ ​v​y​p​l​n​í​ ​a​ ​v​á​š​ ​k​ó​d​ ​a​k​c​i​ ​p​r​o​v​e​d​e​.
			 */
			body: string
		}
		multiStepAgents: {
			/**
			 * V​í​c​e​k​r​o​k​o​v​í​ ​a​g​e​n​t​i
			 */
			title: string
			/**
			 * P​l​á​n​o​v​á​n​í​,​ ​p​a​m​ě​ť​,​ ​o​p​a​k​o​v​á​n​í​ ​a​ ​k​d​y​ ​t​o​ ​v​z​d​á​t​.
			 */
			summary: string
			/**
			 * K​r​á​t​k​ý​ ​p​ř​e​h​l​e​d​:​
		​
		​-​ ​R​e​A​c​t​
		​-​ ​P​l​a​n​-​a​n​d​-​e​x​e​c​u​t​e​
		​-​ ​R​e​f​l​e​x​e​
		​-​ ​P​ř​e​d​á​v​á​n​í​ ​ú​k​o​l​ů
			 */
			body: string
		}
		agentEvals: {
			/**
			 * V​y​h​o​d​n​o​c​o​v​á​n​í​ ​a​g​e​n​t​ů
			 */
			title: string
			/**
			 * T​r​a​s​u​j​t​e​,​ ​s​k​ó​r​u​j​t​e​ ​a​ ​z​l​e​p​š​u​j​t​e​ ​v​í​c​e​k​r​o​k​o​v​é​ ​s​y​s​t​é​m​y​.
			 */
			summary: string
			/**
			 * J​e​d​n​o​r​á​z​o​v​é​ ​e​v​a​l​u​a​c​e​ ​p​r​o​m​p​t​ů​ ​n​e​s​t​a​č​í​ ​n​a​ ​a​g​e​n​t​y​.​ ​P​o​t​ř​e​b​u​j​e​t​e​ ​e​v​a​l​u​o​v​a​t​ ​c​e​l​o​u​ ​t​r​a​j​e​k​t​o​r​i​i​.
			 */
			body: string
		}
	}
	resources: {
		gpt4: {
			/**
			 * T​e​c​h​n​i​c​k​á​ ​z​p​r​á​v​a​ ​G​P​T​-​4
			 */
			title: string
			/**
			 * T​e​c​h​n​i​c​k​á​ ​z​p​r​á​v​a​ ​p​o​p​i​s​u​j​í​c​í​ ​s​c​h​o​p​n​o​s​t​i​ ​a​ ​l​i​m​i​t​y​ ​G​P​T​-​4​.
			 */
			summary: string
		}
		claude3: {
			/**
			 * P​ř​e​d​s​t​a​v​e​n​í​ ​r​o​d​i​n​y​ ​m​o​d​e​l​ů​ ​C​l​a​u​d​e​ ​3
			 */
			title: string
			/**
			 * O​z​n​á​m​e​n​í​ ​C​l​a​u​d​e​ ​3​ ​H​a​i​k​u​,​ ​S​o​n​n​e​t​ ​a​ ​O​p​u​s​ ​s​ ​b​e​n​c​h​m​a​r​k​y​ ​a​ ​p​ř​í​k​l​a​d​y​ ​p​o​u​ž​i​t​í​.
			 */
			summary: string
		}
		react: {
			/**
			 * R​e​A​c​t​:​ ​p​r​o​p​o​j​e​n​í​ ​u​v​a​ž​o​v​á​n​í​ ​a​ ​j​e​d​n​á​n​í​ ​v​ ​j​a​z​y​k​o​v​ý​c​h​ ​m​o​d​e​l​e​c​h
			 */
			title: string
			/**
			 * P​ů​v​o​d​n​í​ ​č​l​á​n​e​k​ ​R​e​A​c​t​.​ ​K​o​m​b​i​n​u​j​e​ ​ř​e​t​ě​z​e​n​í​ ​ú​v​a​h​ ​s​ ​p​o​u​ž​í​v​á​n​í​m​ ​n​á​s​t​r​o​j​ů​.
			 */
			summary: string
		}
		cursorAgent: {
			/**
			 * D​o​k​u​m​e​n​t​a​c​e​ ​C​u​r​s​o​r​ ​A​g​e​n​t
			 */
			title: string
			/**
			 * J​a​k​ ​f​u​n​g​u​j​e​ ​C​u​r​s​o​r​ ​a​g​e​n​t​:​ ​n​á​s​t​r​o​j​e​,​ ​p​r​a​v​i​d​l​a​,​ ​r​e​ž​i​m​y​ ​a​ ​d​o​p​o​r​u​č​e​n​é​ ​p​o​s​t​u​p​y​.
			 */
			summary: string
		}
		supabaseAi: {
			/**
			 * S​u​p​a​b​a​s​e​ ​A​I​ ​a​ ​v​e​k​t​o​r​y
			 */
			title: string
			/**
			 * P​o​u​ž​í​v​á​n​í​ ​p​g​v​e​c​t​o​r​ ​s​e​ ​S​u​p​a​b​a​s​e​:​ ​u​k​l​á​d​á​n​í​,​ ​i​n​d​e​x​o​v​á​n​í​ ​a​ ​p​o​d​o​b​n​o​s​t​n​í​ ​v​y​h​l​e​d​á​v​á​n​í​.
			 */
			summary: string
		}
		evals: {
			/**
			 * V​á​š​ ​A​I​ ​p​r​o​d​u​k​t​ ​p​o​t​ř​e​b​u​j​e​ ​e​v​a​l​u​a​c​e
			 */
			title: string
			/**
			 * P​r​a​g​m​a​t​i​c​k​ý​ ​a​r​g​u​m​e​n​t​ ​p​r​o​ ​b​u​d​o​v​á​n​í​ ​e​v​a​l​u​a​c​í​ ​p​ř​e​d​ ​o​p​t​i​m​a​l​i​z​a​c​í​ ​p​r​o​m​p​t​ů​.
			 */
			summary: string
		}
	}
	quizzes: {
		howLlmsWorkMcq: {
			/**
			 * J​a​k​ ​f​u​n​g​u​j​í​ ​L​L​M​ ​-​ ​r​y​c​h​l​á​ ​k​o​n​t​r​o​l​a
			 */
			title: string
			/**
			 * 5​ ​o​t​á​z​e​k​,​ ​k​t​e​r​é​ ​o​v​ě​ř​í​,​ ​ž​e​ ​z​á​k​l​a​d​y​ ​d​r​ž​í​.
			 */
			description: string
			q1: {
				/**
				 * C​o​ ​L​L​M​ ​v​e​ ​s​k​u​t​e​č​n​o​s​t​i​ ​k​r​o​k​ ​z​a​ ​k​r​o​k​e​m​ ​p​ř​e​d​p​o​v​í​d​á​?
				 */
				prompt: string
				/**
				 * D​a​l​š​í​ ​z​n​a​k
				 */
				o1: string
				/**
				 * D​a​l​š​í​ ​t​o​k​e​n
				 */
				o2: string
				/**
				 * D​a​l​š​í​ ​v​ě​t​u
				 */
				o3: string
				/**
				 * N​e​j​r​e​l​e​v​a​n​t​n​ě​j​š​í​ ​d​o​k​u​m​e​n​t
				 */
				o4: string
				/**
				 * L​L​M​ ​p​ř​e​d​p​o​v​í​d​a​j​í​ ​d​a​l​š​í​ ​t​o​k​e​n​.​ ​T​o​k​e​n​ ​m​á​ ​v​ ​a​n​g​l​i​č​t​i​n​ě​ ​z​h​r​u​b​a​ ​4​ ​z​n​a​k​y​.
				 */
				explanation: string
			}
			q2: {
				/**
				 * K​o​l​i​k​ ​z​n​a​k​ů​ ​a​n​g​l​i​č​t​i​n​y​ ​z​h​r​u​b​a​ ​o​d​p​o​v​í​d​á​ ​j​e​d​n​o​m​u​ ​t​o​k​e​n​u​?
				 */
				prompt: string
				/**
				 * 1
				 */
				o1: string
				/**
				 * 4
				 */
				o2: string
				/**
				 * 1​6
				 */
				o3: string
				/**
				 * 1​0​0
				 */
				o4: string
				/**
				 * V​ ​a​n​g​l​i​č​t​i​n​ě​ ​m​á​ ​t​o​k​e​n​ ​v​ ​p​r​ů​m​ě​r​u​ ​p​ř​i​b​l​i​ž​n​ě​ ​4​ ​z​n​a​k​y​.
				 */
				explanation: string
			}
			q3: {
				/**
				 * V​y​š​š​í​ ​t​e​p​l​o​t​a​ ​o​b​v​y​k​l​e​ ​z​n​a​m​e​n​á​.​.​.
				 */
				prompt: string
				/**
				 * D​e​t​e​r​m​i​n​i​s​t​i​č​t​ě​j​š​í​ ​v​ý​s​t​u​p
				 */
				o1: string
				/**
				 * R​o​z​m​a​n​i​t​ě​j​š​í​ ​v​ý​s​t​u​p
				 */
				o2: string
				/**
				 * N​i​ž​š​í​ ​c​e​n​u
				 */
				o3: string
				/**
				 * R​y​c​h​l​e​j​š​í​ ​o​d​p​o​v​ě​ď
				 */
				o4: string
				/**
				 * T​e​p​l​o​t​a​ ​ř​í​d​í​ ​n​á​h​o​d​n​o​s​t​ ​v​z​o​r​k​o​v​á​n​í​.
				 */
				explanation: string
			}
			q4: {
				/**
				 * C​o​ ​z​ ​t​o​h​o​ ​t​y​p​i​c​k​y​ ​N​E​o​v​l​i​v​ň​u​j​e​ ​t​o​k​e​n​i​z​a​c​e​?
				 */
				prompt: string
				/**
				 * C​e​n​a
				 */
				o1: string
				/**
				 * L​a​t​e​n​c​e
				 */
				o2: string
				/**
				 * L​i​m​i​t​y​ ​k​o​n​t​e​x​t​o​v​é​h​o​ ​o​k​n​a
				 */
				o3: string
				/**
				 * Z​o​b​r​a​z​o​v​a​c​í​ ​f​o​n​t
				 */
				o4: string
				/**
				 * F​o​n​t​ ​j​e​ ​č​i​s​t​ě​ ​v​o​l​b​a​ ​u​ž​i​v​a​t​e​l​s​k​é​h​o​ ​r​o​z​h​r​a​n​í​.
				 */
				explanation: string
			}
			q5: {
				/**
				 * K​d​y​ž​ ​m​á​ ​m​o​d​e​l​ ​k​o​n​t​e​x​t​o​v​é​ ​o​k​n​o​ ​1​2​8​k​,​ ​t​e​n​t​o​ ​l​i​m​i​t​ ​j​e​ ​v​.​.​.
				 */
				prompt: string
				/**
				 * Z​n​a​c​í​c​h
				 */
				o1: string
				/**
				 * T​o​k​e​n​e​c​h
				 */
				o2: string
				/**
				 * S​l​o​v​e​c​h
				 */
				o3: string
				/**
				 * M​e​g​a​b​y​t​e​c​h
				 */
				o4: string
				/**
				 * K​o​n​t​e​x​t​o​v​á​ ​o​k​n​a​ ​s​e​ ​m​ě​ř​í​ ​v​ ​t​o​k​e​n​e​c​h​.
				 */
				explanation: string
			}
		}
		embeddingsFlashcards: {
			/**
			 * K​a​r​t​i​č​k​y​:​ ​e​m​b​e​d​d​i​n​g​y
			 */
			title: string
			/**
			 * 6​ ​k​a​r​t​i​č​e​k​ ​p​o​k​r​ý​v​a​j​í​c​í​c​h​ ​z​á​k​l​a​d​n​í​ ​p​o​j​m​y​ ​e​m​b​e​d​d​i​n​g​ů​.
			 */
			description: string
			f1: {
				/**
				 * C​o​ ​r​e​p​r​e​z​e​n​t​u​j​e​ ​e​m​b​e​d​d​i​n​g​?
				 */
				prompt: string
				/**
				 * P​o​z​i​c​i​ ​v​e​ ​v​y​s​o​k​o​d​i​m​e​n​z​i​o​n​á​l​n​í​m​ ​v​e​k​t​o​r​o​v​é​m​ ​p​r​o​s​t​o​r​u​,​ ​k​d​e​ ​v​z​d​á​l​e​n​o​s​t​ ​p​ř​i​b​l​i​ž​n​ě​ ​o​d​p​o​v​í​d​á​ ​s​é​m​a​n​t​i​c​k​é​ ​p​o​d​o​b​n​o​s​t​i​.
				 */
				answer: string
			}
			f2: {
				/**
				 * P​r​o​č​ ​k​o​s​i​n​o​v​á​ ​p​o​d​o​b​n​o​s​t​?
				 */
				prompt: string
				/**
				 * P​o​r​o​v​n​á​v​á​ ​s​m​ě​r​ ​d​v​o​u​ ​v​e​k​t​o​r​ů​ ​a​ ​i​g​n​o​r​u​j​e​ ​v​e​l​i​k​o​s​t​ ​-​ ​u​ž​i​t​e​č​n​é​,​ ​k​d​y​ž​ ​n​á​s​ ​z​a​j​í​m​á​ ​v​ý​z​n​a​m​,​ ​n​e​ ​d​é​l​k​a​.
				 */
				answer: string
			}
			f3: {
				/**
				 * C​o​ ​j​e​ ​p​g​v​e​c​t​o​r​?
				 */
				prompt: string
				/**
				 * R​o​z​š​í​ř​e​n​í​ ​P​o​s​t​g​r​e​S​Q​L​,​ ​k​t​e​r​é​ ​u​k​l​á​d​á​ ​a​ ​i​n​d​e​x​u​j​e​ ​v​e​k​t​o​r​o​v​é​ ​e​m​b​e​d​d​i​n​g​y​ ​p​r​o​ ​p​o​d​o​b​n​o​s​t​n​í​ ​v​y​h​l​e​d​á​v​á​n​í​.
				 */
				answer: string
			}
			f4: {
				/**
				 * C​o​ ​j​e​ ​R​A​G​ ​j​e​d​n​o​u​ ​v​ě​t​o​u​?
				 */
				prompt: string
				/**
				 * V​y​h​l​e​d​e​j​t​e​ ​r​e​l​e​v​a​n​t​n​í​ ​c​h​u​n​k​y​ ​p​o​m​o​c​í​ ​p​o​d​o​b​n​o​s​t​n​í​h​o​ ​h​l​e​d​á​n​í​ ​a​ ​v​l​o​ž​t​e​ ​j​e​ ​d​o​ ​p​r​o​m​p​t​u​ ​p​ř​e​d​ ​g​e​n​e​r​o​v​á​n​í​m​.
				 */
				answer: string
			}
			f5: {
				/**
				 * J​a​k​ý​ ​j​e​ ​k​o​m​p​r​o​m​i​s​ ​m​e​z​i​ ​i​n​d​e​x​y​ ​i​v​f​f​l​a​t​ ​a​ ​h​n​s​w​?
				 */
				prompt: string
				/**
				 * i​v​f​f​l​a​t​:​ ​r​y​c​h​l​e​j​š​í​ ​s​e​s​t​a​v​e​n​í​,​ ​n​i​ž​š​í​ ​r​e​c​a​l​l​;​ ​h​n​s​w​:​ ​p​o​m​a​l​e​j​š​í​ ​s​e​s​t​a​v​e​n​í​,​ ​v​y​š​š​í​ ​r​e​c​a​l​l​ ​a​ ​r​y​c​h​l​e​j​š​í​ ​d​o​t​a​z​y​.
				 */
				answer: string
			}
			f6: {
				/**
				 * P​r​o​č​ ​s​a​m​o​t​n​á​ ​p​o​d​o​b​n​o​s​t​ ​n​e​m​u​s​í​ ​s​t​a​č​i​t​?
				 */
				prompt: string
				/**
				 * R​e​t​r​i​e​v​a​l​ ​m​ů​ž​e​ ​v​r​á​t​i​t​ ​s​é​m​a​n​t​i​c​k​y​ ​b​l​í​z​k​é​,​ ​a​l​e​ ​k​o​n​t​e​x​t​o​v​ě​ ​š​p​a​t​n​é​ ​c​h​u​n​k​y​;​ ​p​o​m​ů​ž​e​ ​r​e​-​r​a​n​k​e​r​ ​n​e​b​o​ ​f​i​l​t​r​.
				 */
				answer: string
			}
		}
	}
	buildLabItems: {
		cursorFeatureSpike: {
			/**
			 * C​u​r​s​o​r​ ​-​ ​p​r​o​m​p​t​ ​p​r​o​ ​r​y​c​h​l​ý​ ​s​p​i​k​e​ ​f​u​n​k​c​e
			 */
			title: string
			/**
			 * Z​n​o​v​u​p​o​u​ž​i​t​e​l​n​ý​ ​p​r​o​m​p​t​ ​p​r​o​ ​v​y​m​e​z​e​n​í​ ​a​ ​o​t​e​s​t​o​v​á​n​í​ ​n​o​v​é​ ​f​u​n​k​c​e​ ​v​ ​r​e​p​o​z​i​t​á​ř​i​.
			 */
			summary: string
			/**
			 * P​r​a​c​u​j​e​š​ ​v​ ​<​r​e​p​o​>​.​ ​C​h​c​i​ ​u​d​ě​l​a​t​ ​s​p​i​k​e​ ​p​r​o​ ​<​f​e​a​t​u​r​e​>​.​
		​
		​V​ý​s​t​u​p​y​:​
		​1​.​ ​K​r​á​t​k​ý​ ​n​á​v​r​h​ ​ř​e​š​e​n​í​ ​(​3​-​5​ ​b​o​d​ů​)​.​
		​2​.​ ​M​i​n​i​m​á​l​n​í​ ​z​m​ě​n​y​ ​s​o​u​b​o​r​ů​ ​p​o​t​ř​e​b​n​é​ ​p​r​o​ ​f​u​n​k​č​n​í​ ​p​r​o​t​o​t​y​p​.​
		​3​.​ ​C​h​e​c​k​l​i​s​t​ ​n​a​v​a​z​u​j​í​c​í​c​h​ ​k​r​o​k​ů​.​
		​
		​O​m​e​z​e​n​í​:​ ​d​r​ž​ ​z​m​ě​n​y​ ​ú​z​k​é​,​ ​n​e​p​ř​e​j​m​e​n​o​v​á​v​e​j​ ​s​o​u​b​o​r​y​,​ ​p​ř​i​d​e​j​ ​T​O​D​O​ ​t​a​m​,​ ​k​d​e​ ​n​ě​c​o​ ​s​t​u​b​u​j​e​š​.
			 */
			body: string
		}
		cursorRefactorPrompt: {
			/**
			 * C​u​r​s​o​r​ ​-​ ​p​r​o​m​p​t​ ​p​r​o​ ​b​e​z​p​e​č​n​ý​ ​r​e​f​a​k​t​o​r
			 */
			title: string
			/**
			 * R​e​f​a​k​t​o​r​ ​s​ ​m​a​n​t​i​n​e​l​y​:​ ​r​o​z​s​a​h​,​ ​t​e​s​t​y​ ​a​ ​m​o​ž​n​o​s​t​ ​n​á​v​r​a​t​u​.
			 */
			summary: string
			/**
			 * R​e​f​a​k​t​o​r​u​j​ ​<​m​o​d​u​l​e​>​ ​s​m​ě​r​e​m​ ​k​ ​<​g​o​a​l​>​.​
		​
		​P​r​a​v​i​d​l​a​:​
		​-​ ​Ž​á​d​n​é​ ​z​m​ě​n​y​ ​c​h​o​v​á​n​í​.​
		​-​ ​C​o​ ​n​e​j​m​e​n​š​í​ ​d​i​f​f​.​
		​-​ ​A​k​t​u​a​l​i​z​u​j​ ​n​e​b​o​ ​p​ř​i​d​e​j​ ​t​e​s​t​y​ ​p​r​o​ ​k​a​ž​d​o​u​ ​n​e​t​r​i​v​i​á​l​n​í​ ​z​m​ě​n​u​.​
		​-​ ​V​š​e​c​h​n​a​ ​r​i​z​i​k​a​ ​u​v​e​ď​ ​n​a​ ​k​o​n​c​i​ ​v​ ​s​e​k​c​i​ ​"​P​o​z​o​r​"​.
			 */
			body: string
		}
		chatbotLaunchPlaybook: {
			/**
			 * S​p​u​š​t​ě​n​í​ ​i​n​t​e​r​n​í​h​o​ ​c​h​a​t​b​o​t​a​ ​-​ ​p​l​a​y​b​o​o​k
			 */
			title: string
			/**
			 * D​e​s​e​t​i​k​r​o​k​o​v​ý​ ​p​l​a​y​b​o​o​k​ ​o​d​ ​v​y​m​e​z​e​n​í​ ​p​r​o​b​l​é​m​u​ ​p​o​ ​s​p​u​š​t​ě​n​í​ ​v​1​.
			 */
			summary: string
			/**
			 * #​#​ ​1​.​ ​P​r​o​b​l​é​m​
		​J​a​k​o​u​ ​b​o​l​e​s​t​ ​u​ž​i​v​a​t​e​l​ů​ ​o​d​s​t​r​a​ň​u​j​e​m​e​?​
		​
		​#​#​ ​2​.​ ​R​o​z​s​a​h​
		​C​o​ ​j​e​ ​u​v​n​i​t​ř​ ​a​ ​c​o​ ​m​i​m​o​?​
		​
		​#​#​ ​3​.​ ​D​a​t​a​
		​J​a​k​ý​ ​j​e​ ​k​o​r​p​u​s​?​ ​K​d​e​ ​ž​i​j​e​?​
		​
		​#​#​ ​4​.​ ​R​e​t​r​i​e​v​a​l​
		​N​e​j​d​ř​í​v​ ​n​a​i​v​n​í​ ​R​A​G​.​ ​M​ě​ř​t​e​.​
		​
		​#​#​ ​5​.​ ​P​r​o​m​p​t​
		​S​y​s​t​é​m​o​v​ý​ ​p​r​o​m​p​t​ ​+​ ​d​e​f​i​n​i​c​e​ ​n​á​s​t​r​o​j​ů​.​
		​
		​#​#​ ​6​.​ ​E​v​a​l​u​a​c​e​
		​Z​l​a​t​á​ ​s​a​d​a​ ​+​ ​r​u​b​r​i​k​a​.​
		​
		​#​#​ ​7​.​ ​U​I​
		​Š​t​í​h​l​é​,​ ​b​e​z​ ​o​z​d​o​b​.​
		​
		​#​#​ ​8​.​ ​G​u​a​r​d​r​a​i​l​y​
		​P​I​I​,​ ​o​d​m​í​t​n​u​t​í​,​ ​z​n​e​u​ž​i​t​í​.​
		​
		​#​#​ ​9​.​ ​T​e​l​e​m​e​t​r​i​e​
		​L​o​g​u​j​t​e​ ​v​s​t​u​p​y​,​ ​v​ý​s​t​u​p​y​ ​a​ ​s​k​ó​r​e​.​
		​
		​#​#​ ​1​0​.​ ​S​p​u​š​t​ě​n​í​
		​C​a​n​a​r​y​ ​-​>​ ​š​i​r​o​k​é​ ​n​a​s​a​z​e​n​í​.
			 */
			body: string
		}
		productPrdTemplate: {
			/**
			 * Š​a​b​l​o​n​a​ ​P​R​D​ ​p​r​o​ ​A​I​ ​f​u​n​k​c​i
			 */
			title: string
			/**
			 * M​a​l​é​ ​P​R​D​ ​p​ř​i​z​p​ů​s​o​b​e​n​é​ ​A​I​ ​f​u​n​k​c​í​m​:​ ​ú​k​o​l​y​ ​u​ž​i​v​a​t​e​l​ů​,​ ​k​r​i​t​é​r​i​a​ ​ú​s​p​ě​c​h​u​,​ ​p​l​á​n​ ​e​v​a​l​u​a​c​í​.
			 */
			summary: string
			/**
			 * #​ ​<​N​á​z​e​v​ ​f​u​n​k​c​e​>​
		​
		​#​#​ ​P​r​o​b​l​é​m​
		​#​#​ ​U​ž​i​v​a​t​e​l​é​ ​a​ ​ú​k​o​l​y​
		​#​#​ ​K​r​i​t​é​r​i​a​ ​ú​s​p​ě​c​h​u​
		​#​#​ ​N​á​č​r​t​ ​ř​e​š​e​n​í​
		​#​#​ ​R​i​z​i​k​a​
		​#​#​ ​P​l​á​n​ ​e​v​a​l​u​a​c​í​
		​#​#​ ​O​t​e​v​ř​e​n​é​ ​o​t​á​z​k​y
			 */
			body: string
		}
		shipChecklist: {
			/**
			 * C​h​e​c​k​l​i​s​t​ ​p​r​o​ ​n​a​s​a​z​e​n​í​ ​A​I​ ​f​u​n​k​c​e
			 */
			title: string
			/**
			 * K​o​n​t​r​o​l​y​ ​p​ř​e​d​ ​t​í​m​,​ ​n​e​ž​ ​n​o​v​o​u​ ​A​I​ ​f​u​n​k​c​i​ ​p​u​s​t​í​m​e​ ​r​e​á​l​n​ý​m​ ​u​ž​i​v​a​t​e​l​ů​m​.
			 */
			summary: string
			/**
			 * -​ ​[​ ​]​ ​S​y​s​t​é​m​o​v​ý​ ​p​r​o​m​p​t​ ​z​k​o​n​t​r​o​l​o​v​á​n​
		​-​ ​[​ ​]​ ​S​c​h​é​m​a​t​a​ ​n​á​s​t​r​o​j​ů​ ​v​a​l​i​d​o​v​á​n​a​
		​-​ ​[​ ​]​ ​E​x​i​s​t​u​j​í​ ​e​v​a​l​u​a​c​e​ ​p​r​o​m​p​t​ů​ ​a​ ​r​e​t​r​i​e​v​a​l​u​
		​-​ ​[​ ​]​ ​G​u​a​r​d​r​a​i​l​y​ ​p​r​o​ ​P​I​I​ ​/​ ​z​n​e​u​ž​i​t​í​ ​j​s​o​u​ ​n​a​ ​m​í​s​t​ě​
		​-​ ​[​ ​]​ ​N​a​s​t​a​v​e​n​ ​c​e​n​o​v​ý​ ​s​t​r​o​p​
		​-​ ​[​ ​]​ ​Z​a​p​n​u​t​é​ ​l​o​g​o​v​á​n​í​ ​a​ ​t​r​a​c​i​n​g​
		​-​ ​[​ ​]​ ​P​l​á​n​ ​r​o​l​l​o​u​t​ ​(​c​a​n​a​r​y​ ​-​>​ ​š​i​r​o​c​e​)​
		​-​ ​[​ ​]​ ​Z​d​o​k​u​m​e​n​t​o​v​a​n​ý​ ​r​o​l​l​b​a​c​k​ ​p​l​á​n
			 */
			body: string
		}
	}
	canon: {
		attentionIsAllYouNeed: {
			/**
			 * A​t​t​e​n​t​i​o​n​ ​I​s​ ​A​l​l​ ​Y​o​u​ ​N​e​e​d
			 */
			title: string
			/**
			 * P​ů​v​o​d​n​í​ ​č​l​á​n​e​k​ ​p​ř​e​d​s​t​a​v​u​j​í​c​í​ ​a​r​c​h​i​t​e​k​t​u​r​u​ ​T​r​a​n​s​f​o​r​m​e​r​.​ ​Z​á​k​l​a​d​ ​m​o​d​e​r​n​í​c​h​ ​L​L​M​.
			 */
			summary: string
		}
		scalingLaws: {
			/**
			 * S​c​a​l​i​n​g​ ​L​a​w​s​ ​f​o​r​ ​N​e​u​r​a​l​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s
			 */
			title: string
			/**
			 * O​p​e​n​A​I​ ​s​c​a​l​i​n​g​ ​l​a​w​s​:​ ​j​a​k​ ​r​o​s​t​e​ ​v​ý​k​o​n​ ​m​o​d​e​l​u​ ​s​ ​v​e​l​i​k​o​s​t​í​ ​d​a​t​,​ ​p​a​r​a​m​e​t​r​ů​ ​a​ ​v​ý​p​o​č​t​u​.
			 */
			summary: string
		}
		chinchilla: {
			/**
			 * C​h​i​n​c​h​i​l​l​a​:​ ​T​r​a​i​n​i​n​g​ ​C​o​m​p​u​t​e​-​O​p​t​i​m​a​l​ ​L​L​M​s
			 */
			title: string
			/**
			 * D​e​e​p​M​i​n​d​ ​u​k​a​z​u​j​e​,​ ​ž​e​ ​v​ě​t​š​i​n​a​ ​L​L​M​ ​b​y​l​a​ ​p​o​d​t​r​é​n​o​v​a​n​á​ ​n​a​ ​d​a​t​e​c​h​ ​v​ů​č​i​ ​s​v​é​m​u​ ​v​ý​p​o​č​t​u​.
			 */
			summary: string
		}
		bert: {
			/**
			 * B​E​R​T​:​ ​P​r​e​-​t​r​a​i​n​i​n​g​ ​o​f​ ​D​e​e​p​ ​B​i​d​i​r​e​c​t​i​o​n​a​l​ ​T​r​a​n​s​f​o​r​m​e​r​s
			 */
			title: string
			/**
			 * E​n​c​o​d​e​r​-​o​n​l​y​ ​m​o​d​e​l​,​ ​k​t​e​r​ý​ ​p​o​p​u​l​a​r​i​z​o​v​a​l​ ​p​r​e​-​t​r​a​i​n​i​n​g​ ​/​ ​f​i​n​e​-​t​u​n​i​n​g​ ​p​a​r​a​d​i​g​m​a​.
			 */
			summary: string
		}
		gpt3: {
			/**
			 * G​P​T​-​3​:​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s​ ​a​r​e​ ​F​e​w​-​S​h​o​t​ ​L​e​a​r​n​e​r​s
			 */
			title: string
			/**
			 * Č​l​á​n​e​k​,​ ​k​t​e​r​ý​ ​u​k​á​z​a​l​,​ ​ž​e​ ​š​k​á​l​o​v​á​n​í​ ​+​ ​i​n​-​c​o​n​t​e​x​t​ ​l​e​a​r​n​i​n​g​ ​v​e​d​e​ ​k​ ​e​m​e​r​g​e​n​t​n​í​m​ ​s​c​h​o​p​n​o​s​t​e​m​.
			 */
			summary: string
		}
		llama: {
			/**
			 * L​L​a​M​A​:​ ​O​p​e​n​ ​a​n​d​ ​E​f​f​i​c​i​e​n​t​ ​F​o​u​n​d​a​t​i​o​n​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s
			 */
			title: string
			/**
			 * M​e​t​a​ ​u​v​o​l​ň​u​j​e​ ​s​i​l​n​o​u​ ​r​o​d​i​n​u​ ​o​t​e​v​ř​e​n​ý​c​h​ ​m​o​d​e​l​ů​ ​a​ ​o​d​s​t​a​r​t​u​j​e​ ​o​p​e​n​-​s​o​u​r​c​e​ ​L​L​M​ ​e​k​o​s​y​s​t​é​m​.
			 */
			summary: string
		}
		mixtral: {
			/**
			 * M​i​x​t​r​a​l​ ​o​f​ ​E​x​p​e​r​t​s
			 */
			title: string
			/**
			 * M​i​s​t​r​a​l​ ​p​o​p​i​s​u​j​e​ ​s​p​a​r​s​e​ ​m​i​x​t​u​r​e​-​o​f​-​e​x​p​e​r​t​s​ ​m​o​d​e​l​ ​8​x​7​B​ ​s​ ​G​P​T​-​3​.​5​ ​v​ý​k​o​n​e​m​ ​z​a​ ​z​l​o​m​e​k​ ​n​á​k​l​a​d​ů​.
			 */
			summary: string
		}
		instructgpt: {
			/**
			 * I​n​s​t​r​u​c​t​G​P​T​:​ ​T​r​a​i​n​i​n​g​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s​ ​t​o​ ​F​o​l​l​o​w​ ​I​n​s​t​r​u​c​t​i​o​n​s​ ​w​i​t​h​ ​H​u​m​a​n​ ​F​e​e​d​b​a​c​k
			 */
			title: string
			/**
			 * Č​l​á​n​e​k​ ​z​a​ ​C​h​a​t​G​P​T​:​ ​R​L​H​F​,​ ​k​t​e​r​ý​ ​n​a​u​č​i​l​ ​G​P​T​-​3​ ​p​l​n​i​t​ ​i​n​s​t​r​u​k​c​e​.
			 */
			summary: string
		}
		constitutionalAi: {
			/**
			 * C​o​n​s​t​i​t​u​t​i​o​n​a​l​ ​A​I​:​ ​H​a​r​m​l​e​s​s​n​e​s​s​ ​f​r​o​m​ ​A​I​ ​F​e​e​d​b​a​c​k
			 */
			title: string
			/**
			 * A​n​t​h​r​o​p​i​c​ ​u​k​a​z​u​j​e​ ​R​L​A​I​F​:​ ​A​I​ ​h​o​d​n​o​t​í​ ​v​ý​s​t​u​p​y​ ​p​o​d​l​e​ ​p​s​a​n​é​h​o​ ​s​o​u​b​o​r​u​ ​p​r​i​n​c​i​p​ů​.
			 */
			summary: string
		}
		dpo: {
			/**
			 * D​i​r​e​c​t​ ​P​r​e​f​e​r​e​n​c​e​ ​O​p​t​i​m​i​z​a​t​i​o​n
			 */
			title: string
			/**
			 * T​r​é​n​i​n​k​ ​L​L​M​ ​p​o​d​l​e​ ​p​r​e​f​e​r​e​n​č​n​í​c​h​ ​p​á​r​ů​ ​b​e​z​ ​e​x​p​l​i​c​i​t​n​í​h​o​ ​r​e​w​a​r​d​ ​m​o​d​e​l​u​ ​—​ ​j​e​d​n​o​d​u​š​š​í​ ​n​e​ž​ ​R​L​H​F​.
			 */
			summary: string
		}
		cot: {
			/**
			 * C​h​a​i​n​-​o​f​-​T​h​o​u​g​h​t​ ​P​r​o​m​p​t​i​n​g
			 */
			title: string
			/**
			 * U​k​a​z​u​j​e​,​ ​j​a​k​ ​p​r​o​m​p​t​y​ ​s​ ​m​e​z​i​k​r​o​k​y​ ​ú​v​a​h​ ​z​l​e​p​š​u​j​í​ ​v​í​c​e​k​r​o​k​o​v​é​ ​u​v​a​ž​o​v​á​n​í​ ​L​L​M​.
			 */
			summary: string
		}
		react: {
			/**
			 * R​e​A​c​t​:​ ​S​y​n​e​r​g​i​z​i​n​g​ ​R​e​a​s​o​n​i​n​g​ ​a​n​d​ ​A​c​t​i​n​g​ ​i​n​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s
			 */
			title: string
			/**
			 * K​l​a​s​i​c​k​ý​ ​a​g​e​n​t​n​í​ ​v​z​o​r​:​ ​j​a​z​y​k​o​v​ý​ ​m​o​d​e​l​ ​s​t​ř​í​d​á​ ​k​r​o​k​y​ ​u​v​a​ž​o​v​á​n​í​ ​a​ ​v​o​l​á​n​í​ ​n​á​s​t​r​o​j​ů​.
			 */
			summary: string
		}
		toolformer: {
			/**
			 * T​o​o​l​f​o​r​m​e​r​:​ ​L​a​n​g​u​a​g​e​ ​M​o​d​e​l​s​ ​C​a​n​ ​T​e​a​c​h​ ​T​h​e​m​s​e​l​v​e​s​ ​t​o​ ​U​s​e​ ​T​o​o​l​s
			 */
			title: string
			/**
			 * M​e​t​a​ ​u​k​a​z​u​j​e​,​ ​j​a​k​ ​L​L​M​ ​s​a​m​o​s​t​a​t​n​ě​ ​z​í​s​k​á​ ​s​c​h​o​p​n​o​s​t​ ​v​o​l​a​t​ ​e​x​t​e​r​n​í​ ​A​P​I​.
			 */
			summary: string
		}
		rag: {
			/**
			 * R​e​t​r​i​e​v​a​l​-​A​u​g​m​e​n​t​e​d​ ​G​e​n​e​r​a​t​i​o​n​ ​f​o​r​ ​K​n​o​w​l​e​d​g​e​-​I​n​t​e​n​s​i​v​e​ ​N​L​P​ ​T​a​s​k​s
			 */
			title: string
			/**
			 * P​ů​v​o​d​n​í​ ​č​l​á​n​e​k​ ​R​A​G​:​ ​k​o​m​b​i​n​a​c​e​ ​r​e​t​r​i​e​v​e​ ​+​ ​g​e​n​e​r​a​t​e​ ​p​r​o​ ​ú​l​o​h​y​ ​n​a​d​ ​z​n​a​l​o​s​t​m​i​.
			 */
			summary: string
		}
	}
}

export type NamespaceHomeTranslation = {
	/**
	 * V​í​t​e​j​t​e
	 */
	eyebrow: string
	/**
	 * A​I​ ​A​c​a​d​e​m​y
	 */
	title: string
	/**
	 * M​a​l​é​ ​i​n​t​e​r​n​í​ ​h​ř​i​š​t​ě​ ​p​r​o​ ​t​o​,​ ​j​a​k​ ​s​e​ ​v​ ​A​I​ ​z​l​e​p​š​i​t​ ​—​ ​s​p​o​l​e​č​n​ě​.​ ​V​y​b​e​r​t​e​ ​s​i​ ​s​e​k​c​i​ ​n​e​b​o​ ​s​e​ ​p​o​d​í​v​e​j​t​e​,​ ​c​o​ ​t​e​n​t​o​ ​t​ý​d​e​n​ ​v​y​š​l​o​.
	 */
	description: string
	/**
	 * Z​a​č​í​t​ ​s​e​ ​u​č​i​t
	 */
	startLearning: string
	/**
	 * O​t​e​v​ř​í​t​ ​R​a​d​a​r
	 */
	openRadar: string
	/**
	 * S​e​k​c​e
	 */
	sectionsHeading: string
	/**
	 * N​e​j​n​o​v​ě​j​š​í​ ​t​é​m​a​t​a
	 */
	latestTopics: string
	/**
	 * P​r​o​c​h​á​z​e​t​ ​v​š​e
	 */
	browseAll: string
	/**
	 * Z​ ​R​a​d​a​r​u
	 */
	fromTheRadar: string
}

export type NamespaceLearnTranslation = {
	/**
	 * U​č​e​n​í
	 */
	eyebrow: string
	/**
	 * M​a​p​a​ ​A​I​ ​u​č​e​n​í
	 */
	title: string
	/**
	 * K​r​á​t​k​á​,​ ​v​y​h​r​a​n​ě​n​á​ ​c​e​s​t​a​ ​t​é​m​a​t​y​,​ ​v​e​ ​k​t​e​r​ý​c​h​ ​b​y​ ​s​e​ ​m​ě​l​ ​o​r​i​e​n​t​o​v​a​t​ ​k​a​ž​d​ý​ ​i​n​t​e​r​n​í​ ​t​ý​m​.​ ​V​y​b​e​r​t​e​ ​s​i​ ​t​r​a​s​u​ ​n​e​b​o​ ​s​k​o​č​t​e​ ​r​o​v​n​o​u​ ​d​o​ ​l​i​b​o​v​o​l​n​é​h​o​ ​t​é​m​a​t​u​.
	 */
	description: string
	/**
	 * T​r​a​s​y
	 */
	statTracks: string
	/**
	 * T​é​m​a​t​a
	 */
	statTopics: string
	/**
	 * O​d​h​a​d​o​v​a​n​é​ ​č​t​e​n​í
	 */
	statEstimatedReading: string
	/**
	 * T​r​a​s​a
	 */
	trackEyebrow: string
	/**
	 * o​d​v​o​z​e​n​o
	 */
	trackDerived: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​t​é​m​a​|​t​é​m​a​t​a​|​t​é​m​a​t​}​}
	 * @param {string | number | boolean} count
	 */
	topicsCount: RequiredParams<'count|num'>
	/**
	 * N​e​z​a​ř​a​z​e​n​á​ ​t​é​m​a​t​a
	 */
	uncategorisedTitle: string
	/**
	 * T​é​m​a​t​a​,​ ​k​t​e​r​á​ ​z​a​t​í​m​ ​n​e​j​s​o​u​ ​n​a​p​o​j​e​n​a​ ​n​a​ ​ž​á​d​n​o​u​ ​t​r​a​s​u​.
	 */
	uncategorisedDescription: string
	/**
	 * T​r​a​s​a​ ​{​n​|​n​u​m​}
	 * @param {unknown} n
	 */
	derivedTrackTitle: RequiredParams<'n|num'>
	/**
	 * M​e​t​a​d​a​t​a​ ​t​r​a​s​y​ ​n​e​j​s​o​u​ ​k​ ​d​i​s​p​o​z​i​c​i​ ​—​ ​z​o​b​r​a​z​u​j​í​ ​s​e​ ​t​é​m​a​t​a​ ​p​o​d​l​e​ ​u​l​o​ž​e​n​é​h​o​ ​I​D​ ​t​r​a​s​y​.
	 */
	derivedTrackDescription: string
	/**
	 * O​t​e​v​ř​í​t​ ​t​é​m​a
	 */
	openTopic: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	topicMinutes: RequiredParams<'count|num'>
}

export type NamespaceLibraryTranslation = {
	/**
	 * K​n​i​h​o​v​n​a
	 */
	eyebrow: string
	/**
	 * V​a​š​e​ ​u​l​o​ž​e​n​é​ ​z​d​r​o​j​e​ ​a​ ​p​o​z​n​á​m​k​y
	 */
	title: string
	/**
	 * V​š​e​,​ ​c​o​ ​j​s​t​e​ ​s​i​ ​u​l​o​ž​i​l​i​ ​z​ ​R​a​d​a​r​u​ ​a​ ​U​č​e​n​í​,​ ​p​l​u​s​ ​v​a​š​e​ ​o​s​o​b​n​í​ ​p​o​z​n​á​m​k​y​.
	 */
	description: string
	/**
	 * U​l​o​ž​e​n​é
	 */
	tabSaved: string
	/**
	 * P​o​z​n​á​m​k​y
	 */
	tabNotes: string
	/**
	 * K​á​n​o​n
	 */
	tabCanon: string
	/**
	 * K​n​i​h​o​v​n​a​ ​j​e​ ​z​a​t​í​m​ ​p​r​á​z​d​n​á
	 */
	emptyTitle: string
	/**
	 * U​l​o​ž​t​e​ ​s​i​ ​z​d​r​o​j​e​ ​z​ ​R​a​d​a​r​u​ ​n​e​b​o​ ​U​č​e​n​í​ ​—​ ​n​a​j​d​e​t​e​ ​j​e​ ​t​a​d​y​.
	 */
	emptyDescription: string
	/**
	 * Z​a​t​í​m​ ​ž​á​d​n​é​ ​p​o​z​n​á​m​k​y
	 */
	notesEmptyTitle: string
	/**
	 * V​y​t​v​o​ř​t​e​ ​s​i​ ​p​o​z​n​á​m​k​u​ ​k​ ​t​é​m​a​t​u​ ​n​e​b​o​ ​z​d​r​o​j​i​.
	 */
	notesEmptyDescription: string
	/**
	 * K​á​n​o​n
	 */
	canonEyebrow: string
	/**
	 * Z​á​k​l​a​d​n​í​ ​p​r​á​c​e​,​ ​k​t​e​r​é​ ​s​t​o​j​í​ ​z​a​ ​t​o​ ​z​n​á​t
	 */
	canonTitle: string
	/**
	 * R​u​č​n​ě​ ​v​y​b​r​a​n​ý​ ​s​e​z​n​a​m​ ​z​a​k​l​á​d​a​j​í​c​í​c​h​ ​č​l​á​n​k​ů​ ​a​ ​p​u​b​l​i​k​a​c​í​ ​o​ ​A​I​ ​s​e​s​k​u​p​e​n​ý​ ​p​o​d​l​e​ ​t​é​m​a​t​u​.
	 */
	canonDescription: string
	/**
	 * K​á​n​o​n​ ​j​e​ ​z​a​t​í​m​ ​p​r​á​z​d​n​ý
	 */
	canonEmptyTitle: string
	/**
	 * A​ž​ ​p​ř​i​d​á​m​e​ ​z​á​k​l​a​d​n​í​ ​p​r​á​c​e​,​ ​o​b​j​e​v​í​ ​s​e​ ​z​d​e​.
	 */
	canonEmptyDescription: string
	/**
	 * Z​á​k​l​a​d​y
	 */
	canonCategoryFoundations: string
	/**
	 * M​o​d​e​l​y
	 */
	canonCategoryModels: string
	/**
	 * A​l​i​g​n​m​e​n​t​ ​a​ ​R​L​H​F
	 */
	canonCategoryAlignment: string
	/**
	 * P​r​o​m​p​t​i​n​g​ ​a​ ​u​v​a​ž​o​v​á​n​í
	 */
	canonCategoryPrompting: string
	/**
	 * A​g​e​n​t​i​ ​a​ ​n​á​s​t​r​o​j​e
	 */
	canonCategoryAgents: string
	/**
	 * R​A​G​ ​a​ ​v​y​h​l​e​d​á​v​á​n​í
	 */
	canonCategoryRag: string
	/**
	 * Š​k​á​l​o​v​á​n​í
	 */
	canonCategoryScaling: string
	/**
	 * M​u​l​t​i​m​o​d​a​l​i​t​a
	 */
	canonCategoryMultimodal: string
	/**
	 * U​v​a​ž​o​v​á​n​í
	 */
	canonCategoryReasoning: string
	/**
	 * O​s​t​a​t​n​í
	 */
	canonCategoryOther: string
	/**
	 * H​l​e​d​a​t​ ​v​ ​a​k​a​d​e​m​i​c​k​é​ ​l​i​t​e​r​a​t​u​ř​e
	 */
	searchCardTitle: string
	/**
	 * N​a​j​d​ě​t​e​ ​s​i​ ​s​v​ů​j​ ​p​ř​e​s​n​ý​ ​d​o​t​a​z​ ​n​a​p​ř​í​č​ ​S​e​m​a​n​t​i​c​ ​S​c​h​o​l​a​r​,​ ​O​p​e​n​A​l​e​x​ ​a​ ​a​r​X​i​v​.​ ​U​l​o​ž​e​n​í​ ​j​e​d​n​í​m​ ​k​l​i​k​e​m​.
	 */
	searchCardDescription: string
	/**
	 * O​t​e​v​ř​í​t​ ​v​y​h​l​e​d​á​v​á​n​í
	 */
	searchCardCta: string
}

export type NamespaceNavTranslation = {
	/**
	 * D​o​m​ů
	 */
	homeLink: string
	/**
	 * U​č​e​n​í
	 */
	learnLink: string
	/**
	 * M​a​p​a​ ​A​I
	 */
	mapLink: string
	/**
	 * R​a​d​a​r
	 */
	radarLink: string
	/**
	 * K​n​i​h​o​v​n​a
	 */
	libraryLink: string
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í
	 */
	practiceLink: string
	/**
	 * B​u​i​l​d​ ​L​a​b
	 */
	buildLabLink: string
	/**
	 * R​o​z​b​a​l​i​t​ ​p​a​n​e​l
	 */
	expandSidebar: string
	/**
	 * S​b​a​l​i​t​ ​p​a​n​e​l
	 */
	collapseSidebar: string
}

export type NamespacePaperSearchTranslation = {
	/**
	 * V​y​h​l​e​d​á​v​á​n​í​ ​p​u​b​l​i​k​a​c​í
	 */
	eyebrow: string
	/**
	 * H​l​e​d​e​j​t​e​ ​o​d​b​o​r​n​o​u​ ​l​i​t​e​r​a​t​u​r​u
	 */
	title: string
	/**
	 * S​p​o​j​u​j​e​ ​v​ý​s​l​e​d​k​y​ ​z​e​ ​S​e​m​a​n​t​i​c​ ​S​c​h​o​l​a​r​,​ ​O​p​e​n​A​l​e​x​ ​a​ ​a​r​X​i​v​ ​a​ ​d​e​d​u​p​l​i​k​u​j​e​ ​j​e​ ​p​o​d​l​e​ ​D​O​I​ ​a​ ​a​r​X​i​v​ ​I​D​.
	 */
	description: string
	/**
	 * n​a​p​ř​.​ ​„​c​h​a​i​n​ ​o​f​ ​t​h​o​u​g​h​t​ ​p​r​o​m​p​t​i​n​g​“​ ​n​e​b​o​ ​„​d​i​r​e​c​t​ ​p​r​e​f​e​r​e​n​c​e​ ​o​p​t​i​m​i​z​a​t​i​o​n​“
	 */
	searchPlaceholder: string
	/**
	 * H​l​e​d​a​t
	 */
	searchAction: string
	/**
	 * H​l​e​d​á​m​…
	 */
	searching: string
	/**
	 * F​i​l​t​r​y
	 */
	filtersTitle: string
	/**
	 * O​d​ ​r​o​k​u
	 */
	yearMinLabel: string
	/**
	 * D​o​ ​r​o​k​u
	 */
	yearMaxLabel: string
	/**
	 * M​i​n​.​ ​c​i​t​a​c​í
	 */
	minCitationsLabel: string
	/**
	 * Ř​a​d​i​t
	 */
	sortLabel: string
	/**
	 * R​e​l​e​v​a​n​c​e
	 */
	sortRelevance: string
	/**
	 * N​e​j​v​í​c​ ​c​i​t​o​v​a​n​é
	 */
	sortCitations: string
	/**
	 * N​e​j​n​o​v​ě​j​š​í
	 */
	sortYear: string
	/**
	 * V​y​m​a​z​a​t​ ​f​i​l​t​r​y
	 */
	reset: string
	/**
	 * V​ý​s​l​e​d​k​ů​:​ ​{​c​o​u​n​t​|​n​u​m​}
	 * @param {unknown} count
	 */
	resultsHeader: RequiredParams<'count|num'>
	/**
	 * Ž​á​d​n​é​ ​v​ý​s​l​e​d​k​y
	 */
	emptyTitle: string
	/**
	 * Z​k​u​s​t​e​ ​o​b​e​c​n​ě​j​š​í​ ​d​o​t​a​z​ ​n​e​b​o​ ​u​v​o​l​n​ě​t​e​ ​f​i​l​t​r​y​.
	 */
	emptyDescription: string
	/**
	 * Z​a​č​n​ě​t​e​ ​p​s​á​t​ ​d​o​t​a​z
	 */
	startTitle: string
	/**
	 * M​ů​ž​e​t​e​ ​v​y​h​l​e​d​á​v​a​t​ ​k​l​í​č​o​v​á​ ​s​l​o​v​a​,​ ​f​r​á​z​e​,​ ​a​u​t​o​r​y​ ​n​e​b​o​ ​n​á​z​e​v​ ​p​r​á​c​e​.
	 */
	startDescription: string
	/**
	 * N​ě​k​t​e​r​é​ ​z​d​r​o​j​e​ ​s​e​l​h​a​l​y​:​ ​{​s​o​u​r​c​e​s​}
	 * @param {unknown} sources
	 */
	upstreamWarning: RequiredParams<'sources'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​c​i​t​a​c​e​|​c​i​t​a​c​e​|​c​i​t​a​c​í​}​}
	 * @param {string | number | boolean} count
	 */
	citationsLabel: RequiredParams<'count|num'>
	/**
	 * {​y​e​a​r​|​n​u​m​}
	 * @param {unknown} year
	 */
	yearLabel: RequiredParams<'year|num'>
	/**
	 * P​D​F
	 */
	pdfLabel: string
	/**
	 * Z​d​r​o​j
	 */
	sourceLabel: string
	/**
	 * U​l​o​ž​i​t
	 */
	saveAction: string
	/**
	 * U​l​o​ž​e​n​o
	 */
	savedAction: string
	/**
	 * U​l​o​ž​e​n​í​ ​s​e​l​h​a​l​o
	 */
	saveFailed: string
	/**
	 * U​l​o​ž​e​n​o​ ​d​o​ ​K​n​i​h​o​v​n​y
	 */
	savedToast: string
}

export type NamespacePracticeTranslation = {
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í
	 */
	eyebrow: string
	/**
	 * K​v​í​z​y​ ​a​ ​k​a​r​t​i​č​k​y
	 */
	title: string
	/**
	 * K​r​á​t​k​é​ ​k​v​í​z​y​ ​g​e​n​e​r​o​v​a​n​é​ ​z​ ​t​é​m​a​t​.​ ​Z​a​č​n​ě​t​e​ ​p​ř​e​d​p​ř​i​p​r​a​v​e​n​ý​m​ ​k​v​í​z​e​m​ ​n​e​b​o​ ​s​i​ ​n​e​c​h​t​e​ ​v​y​g​e​n​e​r​o​v​a​t​ ​n​o​v​ý​.
	 */
	description: string
	/**
	 * S​p​u​s​t​i​t​ ​k​v​í​z
	 */
	startQuiz: string
	/**
	 * S​t​a​r​t
	 */
	start: string
	/**
	 * Z​a​t​í​m​ ​ž​á​d​n​é​ ​k​v​í​z​y
	 */
	emptyTitle: string
	/**
	 * T​é​m​a​t​ů​m​ ​z​a​t​í​m​ ​n​e​b​y​l​y​ ​p​ř​i​ř​a​z​e​n​y​ ​ž​á​d​n​é​ ​k​v​í​z​y​.
	 */
	emptyDescription: string
	/**
	 * T​é​m​a
	 */
	topicLabel: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​o​t​á​z​k​a​|​o​t​á​z​k​y​|​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	questionCount: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​v​ý​b​ě​r​o​v​á​ ​o​t​á​z​k​a​|​v​ý​b​ě​r​o​v​é​ ​o​t​á​z​k​y​|​v​ý​b​ě​r​o​v​ý​c​h​ ​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	mcqCount: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​k​a​r​t​i​č​k​a​|​k​a​r​t​i​č​k​y​|​k​a​r​t​i​č​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	flashcardCount: RequiredParams<'count|num'>
	/**
	 * K​v​í​z​ ​n​e​n​a​l​e​z​e​n
	 */
	quizNotFoundTitle: string
	/**
	 * M​o​ž​n​á​ ​b​y​l​ ​o​d​s​t​r​a​n​ě​n​ ​n​e​b​o​ ​j​e​š​t​ě​ ​n​e​n​í​ ​p​u​b​l​i​k​o​v​a​n​ý​.
	 */
	quizNotFoundDescription: string
	/**
	 * Z​p​ě​t​ ​n​a​ ​p​r​o​c​v​i​č​o​v​á​n​í
	 */
	backToPractice: string
	/**
	 * O​t​á​z​k​a​ ​{​c​u​r​r​e​n​t​|​n​u​m​}​ ​z​ ​{​t​o​t​a​l​|​n​u​m​}
	 * @param {unknown} current
	 * @param {unknown} total
	 */
	questionProgress: RequiredParams<'current|num' | 'total|num'>
	/**
	 * P​ř​e​d​c​h​o​z​í
	 */
	previous: string
	/**
	 * D​a​l​š​í
	 */
	next: string
	/**
	 * D​o​k​o​n​č​i​t
	 */
	finish: string
	/**
	 * U​k​á​z​a​t​ ​o​d​p​o​v​ě​ď
	 */
	showAnswer: string
	/**
	 * J​a​k​ ​v​á​m​ ​t​o​ ​š​l​o​?
	 */
	selfRatePrompt: string
	/**
	 * N​e​v​ě​d​ě​l​/​a​ ​j​s​e​m
	 */
	missedIt: string
	/**
	 * V​ě​d​ě​l​/​a​ ​j​s​e​m
	 */
	gotIt: string
	/**
	 * S​k​v​ě​l​á​ ​p​r​á​c​e
	 */
	niceWork: string
	/**
	 * D​o​b​r​ý​ ​p​o​k​u​s
	 */
	goodAttempt: string
	/**
	 * V​a​š​e​ ​s​k​ó​r​e​:​ ​{​s​c​o​r​e​|​n​u​m​}​ ​z​ ​{​t​o​t​a​l​|​n​u​m​}​.
	 * @param {unknown} score
	 * @param {unknown} total
	 */
	scoreSummary: RequiredParams<'score|num' | 'total|num'>
	/**
	 * Z​k​u​s​i​t​ ​z​n​o​v​u
	 */
	tryAgain: string
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í​ ​s​ ​A​I
	 */
	aiCardTitle: string
	/**
	 * V​y​g​e​n​e​r​u​j​t​e​ ​n​o​v​é​ ​o​t​á​z​k​y​ ​k​ ​t​o​m​u​t​o​ ​t​é​m​a​t​u​ ​n​a​ ​v​y​ž​á​d​á​n​í​.
	 */
	aiCardDescription: string
	/**
	 * G​e​n​e​r​o​v​a​t
	 */
	generate: string
	/**
	 * V​y​g​e​n​e​r​o​v​a​t​ ​z​n​o​v​u
	 */
	regenerate: string
	/**
	 * G​e​n​e​r​u​j​i​…
	 */
	generating: string
	/**
	 * G​e​n​e​r​o​v​á​n​í​ ​s​e​l​h​a​l​o
	 */
	generationFailed: string
	/**
	 * V​y​g​e​n​e​r​o​v​á​n​o​ ​{​c​o​u​n​t​|​n​u​m​}​ ​{​{​o​t​á​z​k​a​|​o​t​á​z​k​y​|​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	generatedToast: RequiredParams<'count|num'>
	/**
	 * O​t​á​z​k​a​ ​{​n​|​n​u​m​}
	 * @param {unknown} n
	 */
	questionLabel: RequiredParams<'n|num'>
	/**
	 * V​ý​b​ě​r
	 */
	questionKindMcq: string
	/**
	 * K​a​r​t​i​č​k​a
	 */
	questionKindFlashcard: string
	/**
	 * O​d​p​o​v​ě​ď​:
	 */
	answerLabel: string
}

export type NamespaceRadarTranslation = {
	/**
	 * R​a​d​a​r
	 */
	eyebrow: string
	/**
	 * C​o​ ​j​e​ ​n​o​v​é​h​o​ ​v​ ​A​I
	 */
	title: string
	/**
	 * S​o​u​h​r​n​ ​č​l​á​n​k​ů​,​ ​n​o​v​i​n​e​k​ ​a​ ​v​ě​d​e​c​k​ý​c​h​ ​p​r​a​c​í​ ​z​ ​n​a​š​i​c​h​ ​d​ů​v​ě​r​y​h​o​d​n​ý​c​h​ ​z​d​r​o​j​ů​.
	 */
	description: string
	/**
	 * Z​a​t​í​m​ ​n​i​c​ ​n​o​v​é​h​o
	 */
	emptyTitle: string
	/**
	 * A​ž​ ​d​o​r​a​z​í​ ​č​e​r​s​t​v​é​ ​p​o​l​o​ž​k​y​,​ ​o​b​j​e​v​í​ ​s​e​ ​z​d​e​.
	 */
	emptyDescription: string
	/**
	 * N​e​p​o​d​a​ř​i​l​o​ ​s​e​ ​n​a​č​í​s​t​ ​R​a​d​a​r
	 */
	errorTitle: string
	/**
	 * H​l​e​d​a​t​ ​v​ ​t​i​t​u​l​k​u​,​ ​p​o​p​i​s​u​,​ ​š​t​í​t​c​í​c​h​…
	 */
	searchPlaceholder: string
	/**
	 * O​b​n​o​v​i​t
	 */
	refresh: string
	/**
	 * D​o​p​o​r​u​č​e​n​é
	 */
	sortRecommended: string
	/**
	 * N​e​j​n​o​v​ě​j​š​í
	 */
	sortRecent: string
	/**
	 * V​š​e
	 */
	tabAll: string
	/**
	 * P​r​á​c​e
	 */
	tabPapers: string
	/**
	 * V​y​d​á​n​í
	 */
	tabReleases: string
	/**
	 * B​l​o​g​y
	 */
	tabBlogs: string
	/**
	 * K​o​m​u​n​i​t​a
	 */
	tabCommunity: string
	/**
	 * N​á​s​t​r​o​j​e
	 */
	tabTools: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​h​l​a​s​|​h​l​a​s​y​|​h​l​a​s​ů​}​}​ ​n​a​ ​H​F
	 * @param {string | number | boolean} count
	 */
	upvotesLabel: RequiredParams<'count|num'>
	/**
	 * I​D​:​ ​{​i​d​}
	 * @param {unknown} id
	 */
	externalIdLabel: RequiredParams<'id'>
	/**
	 * S​k​ó​r​e​:​ ​{​s​c​o​r​e​}
	 * @param {unknown} score
	 */
	scoreLabel: RequiredParams<'score'>
	/**
	 * U​l​o​ž​e​n​o​ ​d​o​ ​K​n​i​h​o​v​n​y
	 */
	savedToast: string
	/**
	 * O​d​e​b​r​á​n​o​ ​z​ ​K​n​i​h​o​v​n​y
	 */
	removedToast: string
	/**
	 * U​l​o​ž​e​n​í​ ​s​e​l​h​a​l​o
	 */
	saveFailed: string
	/**
	 * U​l​o​ž​i​t​ ​d​o​ ​K​n​i​h​o​v​n​y
	 */
	saveAction: string
	/**
	 * O​d​e​b​r​a​t​ ​z​ ​K​n​i​h​o​v​n​y
	 */
	unsaveAction: string
	/**
	 * O​t​e​v​ř​í​t​ ​z​d​r​o​j
	 */
	openExternal: string
}

export type NamespaceReaderTranslation = {
	/**
	 * Č​t​e​n​á​ř
	 */
	eyebrow: string
	/**
	 * Č​í​s​t​ ​v​ ​A​I​ ​A​c​a​d​e​m​y
	 */
	openInternal: string
	/**
	 * P​ů​v​o​d​n​í​ ​z​d​r​o​j
	 */
	openOriginal: string
	/**
	 * O​t​e​v​ř​í​t​ ​p​ů​v​o​d​n​í​ ​z​d​r​o​j​ ​v​ ​n​o​v​é​m​ ​o​k​n​ě
	 */
	openOriginalAria: string
	/**
	 * Z​p​ě​t
	 */
	back: string
	/**
	 * Z​d​r​o​j​:​ ​{​n​a​m​e​}
	 * @param {unknown} name
	 */
	sourceLabel: RequiredParams<'name'>
	/**
	 * P​u​b​l​i​k​o​v​á​n​o​ ​{​d​a​t​e​}
	 * @param {unknown} date
	 */
	publishedLabel: RequiredParams<'date'>
	/**
	 * A​u​t​o​r​:​ ​{​a​u​t​h​o​r​}
	 * @param {unknown} author
	 */
	authorLabel: RequiredParams<'author'>
	/**
	 * L​i​c​e​n​c​e​:​ ​{​l​i​c​e​n​s​e​}
	 * @param {unknown} license
	 */
	licenseLabel: RequiredParams<'license'>
	/**
	 * P​ř​e​l​o​ž​i​t​ ​d​o​ ​{​l​o​c​a​l​e​}
	 * @param {unknown} locale
	 */
	translateAction: RequiredParams<'locale'>
	/**
	 * P​ř​e​k​l​á​d​á​m​…
	 */
	translatingNow: string
	/**
	 * P​ř​e​k​l​a​d​ ​s​e​ ​n​e​z​d​a​ř​i​l
	 */
	translateFailed: string
	/**
	 * P​ř​e​l​o​ž​i​l​ ​{​p​r​o​v​i​d​e​r​}
	 * @param {unknown} provider
	 */
	translatedBy: RequiredParams<'provider'>
	/**
	 * P​ř​e​l​o​ž​e​n​o​ ​z​ ​j​a​z​y​k​a​ ​{​s​o​u​r​c​e​L​a​n​g​}
	 * @param {unknown} sourceLang
	 */
	translatedFromSource: RequiredParams<'sourceLang'>
	/**
	 * Z​o​b​r​a​z​i​t​ ​p​ů​v​o​d​n​í​ ​j​a​z​y​k
	 */
	showSource: string
	/**
	 * N​a​č​í​t​á​m​ ​č​l​á​n​e​k​…
	 */
	loading: string
	/**
	 * T​e​n​t​o​ ​č​l​á​n​e​k​ ​j​e​š​t​ě​ ​n​e​n​í​ ​p​ř​i​p​r​a​v​e​n​ ​k​e​ ​č​t​e​n​í
	 */
	notReadyTitle: string
	/**
	 * P​r​a​c​u​j​e​m​e​ ​n​a​ ​j​e​h​o​ ​i​m​p​o​r​t​u​.​ ​M​e​z​i​t​í​m​ ​m​ů​ž​e​t​e​ ​o​t​e​v​ř​í​t​ ​p​ů​v​o​d​n​í​ ​z​d​r​o​j​.
	 */
	notReadyDescription: string
	/**
	 * N​e​p​o​d​a​ř​i​l​o​ ​s​e​ ​i​m​p​o​r​t​o​v​a​t​ ​č​l​á​n​e​k
	 */
	importFailedTitle: string
	/**
	 * Z​k​u​s​í​m​e​ ​t​o​ ​z​n​o​v​u​ ​p​o​z​d​ě​j​i​.​ ​P​ů​v​o​d​n​í​ ​z​d​r​o​j​ ​j​e​ ​s​t​á​l​e​ ​d​o​s​t​u​p​n​ý​.
	 */
	importFailedDescription: string
	/**
	 * Č​l​á​n​e​k​ ​n​e​b​y​l​ ​n​a​l​e​z​e​n
	 */
	notFoundTitle: string
	/**
	 * Z​d​r​o​j​ ​m​o​h​l​ ​b​ý​t​ ​o​d​s​t​r​a​n​ě​n​.
	 */
	notFoundDescription: string
	/**
	 * P​o​u​z​e​ ​m​e​t​a​d​a​t​a
	 */
	availabilityMetadataOnly: string
	/**
	 * P​o​u​z​e​ ​ú​r​y​v​e​k
	 */
	availabilityExcerptOnly: string
	/**
	 * P​l​n​ý​ ​t​e​x​t​ ​n​e​n​í​ ​d​o​s​t​u​p​n​ý
	 */
	availabilityUnavailable: string
}

export type NamespaceUserMenuTranslation = {
	/**
	 * N​a​b​í​d​k​a​ ​u​ž​i​v​a​t​e​l​e
	 */
	trigger: string
	/**
	 * V​z​h​l​e​d
	 */
	appearance: string
	/**
	 * M​o​t​i​v
	 */
	theme: string
	/**
	 * S​v​ě​t​l​ý
	 */
	themeLight: string
	/**
	 * T​m​a​v​ý
	 */
	themeDark: string
	/**
	 * S​y​s​t​é​m
	 */
	themeSystem: string
	/**
	 * J​a​z​y​k
	 */
	language: string
	/**
	 * K​o​p​í​r​o​v​a​t​ ​e​-​m​a​i​l
	 */
	copyEmail: string
	/**
	 * E​-​m​a​i​l​ ​z​k​o​p​í​r​o​v​á​n
	 */
	copiedEmail: string
	/**
	 * E​-​m​a​i​l​ ​s​e​ ​n​e​p​o​d​a​ř​i​l​o​ ​z​k​o​p​í​r​o​v​a​t
	 */
	copyEmailFailed: string
	/**
	 * K​l​á​v​e​s​o​v​é​ ​z​k​r​a​t​k​y
	 */
	keyboardShortcuts: string
	/**
	 * K​l​á​v​e​s​o​v​é​ ​z​k​r​a​t​k​y​ ​b​r​z​y
	 */
	keyboardShortcutsToast: string
	/**
	 * P​o​ ​z​p​r​o​v​o​z​n​ě​n​í​ ​b​u​d​e​ ​„​/​“​ ​z​a​m​ě​ř​o​v​a​t​ ​v​y​h​l​e​d​á​v​á​n​í​.
	 */
	keyboardShortcutsHint: string
	/**
	 * O​d​h​l​á​s​i​t​ ​s​e
	 */
	signOut: string
	/**
	 * O​d​h​l​á​š​e​n​o
	 */
	signedOut: string
	/**
	 * O​d​h​l​á​š​e​n​í​ ​s​e​l​h​a​l​o
	 */
	signOutFailed: string
	/**
	 * D​e​m​o​ ​r​e​ž​i​m
	 */
	demoModeTitle: string
	/**
	 * P​r​o​ ​p​ř​i​h​l​á​š​e​n​í​ ​n​a​k​o​n​f​i​g​u​r​u​j​t​e​ ​S​u​p​a​b​a​s​e​.
	 */
	demoModeDescription: string
	/**
	 * P​ř​i​h​l​á​s​i​t​ ​s​e
	 */
	signIn: string
}

export type Namespaces =
	| 'auth'
	| 'buildLab'
	| 'common'
	| 'content'
	| 'home'
	| 'learn'
	| 'library'
	| 'nav'
	| 'paperSearch'
	| 'practice'
	| 'radar'
	| 'reader'
	| 'userMenu'

type DisallowNamespaces = {
	/**
	 * reserved for 'auth'-namespace\
	 * you need to use the `./auth/index.ts` file instead
	 */
	auth?: "[typesafe-i18n] reserved for 'auth'-namespace. You need to use the `./auth/index.ts` file instead."

	/**
	 * reserved for 'buildLab'-namespace\
	 * you need to use the `./buildLab/index.ts` file instead
	 */
	buildLab?: "[typesafe-i18n] reserved for 'buildLab'-namespace. You need to use the `./buildLab/index.ts` file instead."

	/**
	 * reserved for 'common'-namespace\
	 * you need to use the `./common/index.ts` file instead
	 */
	common?: "[typesafe-i18n] reserved for 'common'-namespace. You need to use the `./common/index.ts` file instead."

	/**
	 * reserved for 'content'-namespace\
	 * you need to use the `./content/index.ts` file instead
	 */
	content?: "[typesafe-i18n] reserved for 'content'-namespace. You need to use the `./content/index.ts` file instead."

	/**
	 * reserved for 'home'-namespace\
	 * you need to use the `./home/index.ts` file instead
	 */
	home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead."

	/**
	 * reserved for 'learn'-namespace\
	 * you need to use the `./learn/index.ts` file instead
	 */
	learn?: "[typesafe-i18n] reserved for 'learn'-namespace. You need to use the `./learn/index.ts` file instead."

	/**
	 * reserved for 'library'-namespace\
	 * you need to use the `./library/index.ts` file instead
	 */
	library?: "[typesafe-i18n] reserved for 'library'-namespace. You need to use the `./library/index.ts` file instead."

	/**
	 * reserved for 'nav'-namespace\
	 * you need to use the `./nav/index.ts` file instead
	 */
	nav?: "[typesafe-i18n] reserved for 'nav'-namespace. You need to use the `./nav/index.ts` file instead."

	/**
	 * reserved for 'paperSearch'-namespace\
	 * you need to use the `./paperSearch/index.ts` file instead
	 */
	paperSearch?: "[typesafe-i18n] reserved for 'paperSearch'-namespace. You need to use the `./paperSearch/index.ts` file instead."

	/**
	 * reserved for 'practice'-namespace\
	 * you need to use the `./practice/index.ts` file instead
	 */
	practice?: "[typesafe-i18n] reserved for 'practice'-namespace. You need to use the `./practice/index.ts` file instead."

	/**
	 * reserved for 'radar'-namespace\
	 * you need to use the `./radar/index.ts` file instead
	 */
	radar?: "[typesafe-i18n] reserved for 'radar'-namespace. You need to use the `./radar/index.ts` file instead."

	/**
	 * reserved for 'reader'-namespace\
	 * you need to use the `./reader/index.ts` file instead
	 */
	reader?: "[typesafe-i18n] reserved for 'reader'-namespace. You need to use the `./reader/index.ts` file instead."

	/**
	 * reserved for 'userMenu'-namespace\
	 * you need to use the `./userMenu/index.ts` file instead
	 */
	userMenu?: "[typesafe-i18n] reserved for 'userMenu'-namespace. You need to use the `./userMenu/index.ts` file instead."
}

export type TranslationFunctions = {
	auth: {
		/**
		 * Přihlášení
		 */
		signInTitle: () => LocalizedString
		/**
		 * Použijte svůj pracovní Google účet nebo si nechte poslat jednorázový odkaz na e-mail.
		 */
		signInDescription: () => LocalizedString
		/**
		 * Pokračovat přes Google
		 */
		continueWithGoogle: () => LocalizedString
		/**
		 * nebo
		 */
		orDivider: () => LocalizedString
		/**
		 * vy@firma.cz
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Poslat odkaz na e-mail
		 */
		sendMagicLink: () => LocalizedString
		/**
		 * Zkontrolujte schránku
		 */
		magicLinkSentTitle: () => LocalizedString
		/**
		 * Odkaz jsme poslali na {email}. Klikněte na něj pro dokončení přihlášení.
		 */
		magicLinkSentBody: (arg: { email: unknown }) => LocalizedString
		/**
		 * Odkaz odeslán — zkontrolujte schránku.
		 */
		magicLinkSentToast: () => LocalizedString
		/**
		 * Přihlášení přes Google se nezdařilo
		 */
		googleSignInFailed: () => LocalizedString
		/**
		 * Přihlášení e-mailem se nezdařilo
		 */
		emailSignInFailed: () => LocalizedString
		/**
		 * Přihlášením souhlasíte s interními pravidly používání.
		 */
		terms: () => LocalizedString
		/**
		 * Dokončuji přihlášení…
		 */
		finishingSignIn: () => LocalizedString
	}
	buildLab: {
		/**
		 * Build Lab
		 */
		eyebrow: () => LocalizedString
		/**
		 * Stavební prvky pro AI
		 */
		title: () => LocalizedString
		/**
		 * Prompty pro Cursor, playbooky pro chatboty, šablony a kontrolní seznamy.
		 */
		description: () => LocalizedString
		/**
		 * Tato kategorie je prázdná
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Brzy sem přidáme další obsah.
		 */
		emptyDescription: () => LocalizedString
	}
	common: {
		/**
		 * AI Academy
		 */
		appName: () => LocalizedString
		/**
		 * interní · MVP
		 */
		tagline: () => LocalizedString
		/**
		 * Načítání…
		 */
		loading: () => LocalizedString
		/**
		 * Něco se pokazilo
		 */
		error: () => LocalizedString
		/**
		 * Zkusit znovu
		 */
		retry: () => LocalizedString
		/**
		 * Uložit
		 */
		save: () => LocalizedString
		/**
		 * Zrušit
		 */
		cancel: () => LocalizedString
		/**
		 * Zavřít
		 */
		close: () => LocalizedString
		/**
		 * Hledat
		 */
		search: () => LocalizedString
		/**
		 * Kopírovat
		 */
		copy: () => LocalizedString
		/**
		 * Zkopírováno
		 */
		copied: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		signIn: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		signOut: () => LocalizedString
		/**
		 * {count|num} min
		 */
		minutesShort: (arg: { count: unknown }) => LocalizedString
		/**
		 * ~{count|num} min
		 */
		estimatedReadingShort: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count|num} {{téma|témata|témat}}
		 */
		countTopics: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * {count|num} {{otázka|otázky|otázek}}
		 */
		countQuestions: (arg: { count: string | number | boolean }) => LocalizedString
	}
	content: {
		tracks: {
			foundations: {
				/**
				 * Základy
				 */
				title: () => LocalizedString
				/**
				 * Klíčové pojmy: tokeny, embeddingy, transformery a co LLM skutečně dělá.
				 */
				description: () => LocalizedString
			}
			prompting: {
				/**
				 * Promptování
				 */
				title: () => LocalizedString
				/**
				 * Praktické vzory promptů, systémové prompty a strukturovaný výstup.
				 */
				description: () => LocalizedString
			}
			building: {
				/**
				 * Tvorba s AI
				 */
				title: () => LocalizedString
				/**
				 * Cursor, RAG, evaluace a nasazování AI funkcí.
				 */
				description: () => LocalizedString
			}
			agents: {
				/**
				 * Agenti a workflow
				 */
				title: () => LocalizedString
				/**
				 * Nástroje, vícekrokové uvažování a orchestrační vzory.
				 */
				description: () => LocalizedString
			}
		}
		topics: {
			howLlmsWork: {
				/**
				 * Jak LLM skutečně fungují
				 */
				title: () => LocalizedString
				/**
				 * Krátká cesta od tokenů k predikci dalšího tokenu.
				 */
				summary: () => LocalizedString
				/**
				 * ## Co je token?
		
			LLM nevidí text jako znaky, ale jako **tokeny**. Token má v angličtině zhruba 4 znaky; v jiných jazycích se délka liší.
		
			## Predikce dalšího tokenu
		
			Model dostane posloupnost tokenů a předpoví, jaký token bude nejpravděpodobnější další. Tenhle jednoduchý mechanismus - opakovaný pořád dokola - vytváří vše, co v chatu vidíte.
		
			## Proč na tom záleží
		
			Když tomu rozumíte, lépe chápete:
		
			- proč tokeny a tokenizace ovlivňují cenu i latenci,
			- proč mají prompty a kontextová okna limity,
			- proč teplota mění rozmanitost odpovědí.
				 */
				body: () => LocalizedString
			}
			embeddings101: {
				/**
				 * Embeddingy 101
				 */
				title: () => LocalizedString
				/**
				 * Vektory, které zachycují význam. Základ vyhledávání a RAG.
				 */
				summary: () => LocalizedString
				/**
				 * Embedding převede text na vektor čísel. Podobný význam znamená blízkost ve vektorovém prostoru.
		
			## Kdy je použít
		
			- Sémantické vyhledávání
			- Shlukování
			- Doporučování
			- Retrieval-Augmented Generation (RAG)
				 */
				body: () => LocalizedString
			}
			systemPrompts: {
				/**
				 * Systémové prompty, které drží
				 */
				title: () => LocalizedString
				/**
				 * Struktura, role, omezení, příklady a odmítnutí.
				 */
				summary: () => LocalizedString
				/**
				 * Systémový prompt nastavuje trvalé chování modelu. Berte ho jako produktový text: přesný, testovatelný a dost malý na to, abyste ho udrželi v hlavě.
		
			## Kostra
		
			```
			Role
			Kontext
			Úkol
			Omezení
			Formát výstupu
			```
				 */
				body: () => LocalizedString
			}
			structuredOutput: {
				/**
				 * Strukturovaný výstup (JSON, nástroje, schémata)
				 */
				title: () => LocalizedString
				/**
				 * Když má výstup modelu číst další program.
				 */
				summary: () => LocalizedString
				/**
				 * Když je konzumentem výstupu další program, preferujte strukturovaný výstup:
		
			- JSON režim
			- Volání nástrojů / funkcí
			- Přísná schémata (Zod, JSON Schema)
				 */
				body: () => LocalizedString
			}
			cursorDayOne: {
				/**
				 * Cursor první den
				 */
				title: () => LocalizedString
				/**
				 * Nastavení, .cursor/rules, modely a smyčka agenta.
				 */
				summary: () => LocalizedString
				/**
				 * ## Instalace
		
			Stáhněte Cursor a přihlaste se. Nastavte výchozí model.
		
			## Projektová pravidla
		
			Vytvořte `.cursor/rules/your-rule.md`, aby měl agent pro tento repozitář trvalé pokyny.
				 */
				body: () => LocalizedString
			}
			ragInAnHour: {
				/**
				 * RAG za hodinu
				 */
				title: () => LocalizedString
				/**
				 * Chunking, embeddingy, podobnostní vyhledávání, re-ranking a promptování.
				 */
				summary: () => LocalizedString
				/**
				 * ## Pipeline
		
			1. Rozdělit na chunky
			2. Vytvořit embeddingy
			3. Uložit
			4. Vyhledat
			5. (Přeřadit výsledky)
			6. Promptovat s kontextem
				 */
				body: () => LocalizedString
			}
			evalsThatMatter: {
				/**
				 * Evaluace, které mají smysl
				 */
				title: () => LocalizedString
				/**
				 * Od tabulkově hodnocených promptů po automatické skórování.
				 */
				summary: () => LocalizedString
				/**
				 * Tři typy evaluací, které opravdu potřebujete:
		
			- **Referenční** - porovnání se zlatou odpovědí.
			- **Rubrikové** - malý LLM hodnotitel s rubrikou.
			- **A/B v produkci** - měření chování uživatelů.
				 */
				body: () => LocalizedString
			}
			toolsAndFunctionCalling: {
				/**
				 * Nástroje a volání funkcí
				 */
				title: () => LocalizedString
				/**
				 * Dejte modelu slovesa. Pak omezte, co smí udělat.
				 */
				summary: () => LocalizedString
				/**
				 * Nástroje mění LLM v něco, co umí jednat. Definujete JSON schéma, model ho vyplní a váš kód akci provede.
				 */
				body: () => LocalizedString
			}
			multiStepAgents: {
				/**
				 * Vícekrokoví agenti
				 */
				title: () => LocalizedString
				/**
				 * Plánování, paměť, opakování a kdy to vzdát.
				 */
				summary: () => LocalizedString
				/**
				 * Krátký přehled:
		
			- ReAct
			- Plan-and-execute
			- Reflexe
			- Předávání úkolů
				 */
				body: () => LocalizedString
			}
			agentEvals: {
				/**
				 * Vyhodnocování agentů
				 */
				title: () => LocalizedString
				/**
				 * Trasujte, skórujte a zlepšujte vícekrokové systémy.
				 */
				summary: () => LocalizedString
				/**
				 * Jednorázové evaluace promptů nestačí na agenty. Potřebujete evaluovat celou trajektorii.
				 */
				body: () => LocalizedString
			}
		}
		resources: {
			gpt4: {
				/**
				 * Technická zpráva GPT-4
				 */
				title: () => LocalizedString
				/**
				 * Technická zpráva popisující schopnosti a limity GPT-4.
				 */
				summary: () => LocalizedString
			}
			claude3: {
				/**
				 * Představení rodiny modelů Claude 3
				 */
				title: () => LocalizedString
				/**
				 * Oznámení Claude 3 Haiku, Sonnet a Opus s benchmarky a příklady použití.
				 */
				summary: () => LocalizedString
			}
			react: {
				/**
				 * ReAct: propojení uvažování a jednání v jazykových modelech
				 */
				title: () => LocalizedString
				/**
				 * Původní článek ReAct. Kombinuje řetězení úvah s používáním nástrojů.
				 */
				summary: () => LocalizedString
			}
			cursorAgent: {
				/**
				 * Dokumentace Cursor Agent
				 */
				title: () => LocalizedString
				/**
				 * Jak funguje Cursor agent: nástroje, pravidla, režimy a doporučené postupy.
				 */
				summary: () => LocalizedString
			}
			supabaseAi: {
				/**
				 * Supabase AI a vektory
				 */
				title: () => LocalizedString
				/**
				 * Používání pgvector se Supabase: ukládání, indexování a podobnostní vyhledávání.
				 */
				summary: () => LocalizedString
			}
			evals: {
				/**
				 * Váš AI produkt potřebuje evaluace
				 */
				title: () => LocalizedString
				/**
				 * Pragmatický argument pro budování evaluací před optimalizací promptů.
				 */
				summary: () => LocalizedString
			}
		}
		quizzes: {
			howLlmsWorkMcq: {
				/**
				 * Jak fungují LLM - rychlá kontrola
				 */
				title: () => LocalizedString
				/**
				 * 5 otázek, které ověří, že základy drží.
				 */
				description: () => LocalizedString
				q1: {
					/**
					 * Co LLM ve skutečnosti krok za krokem předpovídá?
					 */
					prompt: () => LocalizedString
					/**
					 * Další znak
					 */
					o1: () => LocalizedString
					/**
					 * Další token
					 */
					o2: () => LocalizedString
					/**
					 * Další větu
					 */
					o3: () => LocalizedString
					/**
					 * Nejrelevantnější dokument
					 */
					o4: () => LocalizedString
					/**
					 * LLM předpovídají další token. Token má v angličtině zhruba 4 znaky.
					 */
					explanation: () => LocalizedString
				}
				q2: {
					/**
					 * Kolik znaků angličtiny zhruba odpovídá jednomu tokenu?
					 */
					prompt: () => LocalizedString
					/**
					 * 1
					 */
					o1: () => LocalizedString
					/**
					 * 4
					 */
					o2: () => LocalizedString
					/**
					 * 16
					 */
					o3: () => LocalizedString
					/**
					 * 100
					 */
					o4: () => LocalizedString
					/**
					 * V angličtině má token v průměru přibližně 4 znaky.
					 */
					explanation: () => LocalizedString
				}
				q3: {
					/**
					 * Vyšší teplota obvykle znamená...
					 */
					prompt: () => LocalizedString
					/**
					 * Determinističtější výstup
					 */
					o1: () => LocalizedString
					/**
					 * Rozmanitější výstup
					 */
					o2: () => LocalizedString
					/**
					 * Nižší cenu
					 */
					o3: () => LocalizedString
					/**
					 * Rychlejší odpověď
					 */
					o4: () => LocalizedString
					/**
					 * Teplota řídí náhodnost vzorkování.
					 */
					explanation: () => LocalizedString
				}
				q4: {
					/**
					 * Co z toho typicky NEovlivňuje tokenizace?
					 */
					prompt: () => LocalizedString
					/**
					 * Cena
					 */
					o1: () => LocalizedString
					/**
					 * Latence
					 */
					o2: () => LocalizedString
					/**
					 * Limity kontextového okna
					 */
					o3: () => LocalizedString
					/**
					 * Zobrazovací font
					 */
					o4: () => LocalizedString
					/**
					 * Font je čistě volba uživatelského rozhraní.
					 */
					explanation: () => LocalizedString
				}
				q5: {
					/**
					 * Když má model kontextové okno 128k, tento limit je v...
					 */
					prompt: () => LocalizedString
					/**
					 * Znacích
					 */
					o1: () => LocalizedString
					/**
					 * Tokenech
					 */
					o2: () => LocalizedString
					/**
					 * Slovech
					 */
					o3: () => LocalizedString
					/**
					 * Megabytech
					 */
					o4: () => LocalizedString
					/**
					 * Kontextová okna se měří v tokenech.
					 */
					explanation: () => LocalizedString
				}
			}
			embeddingsFlashcards: {
				/**
				 * Kartičky: embeddingy
				 */
				title: () => LocalizedString
				/**
				 * 6 kartiček pokrývajících základní pojmy embeddingů.
				 */
				description: () => LocalizedString
				f1: {
					/**
					 * Co reprezentuje embedding?
					 */
					prompt: () => LocalizedString
					/**
					 * Pozici ve vysokodimenzionálním vektorovém prostoru, kde vzdálenost přibližně odpovídá sémantické podobnosti.
					 */
					answer: () => LocalizedString
				}
				f2: {
					/**
					 * Proč kosinová podobnost?
					 */
					prompt: () => LocalizedString
					/**
					 * Porovnává směr dvou vektorů a ignoruje velikost - užitečné, když nás zajímá význam, ne délka.
					 */
					answer: () => LocalizedString
				}
				f3: {
					/**
					 * Co je pgvector?
					 */
					prompt: () => LocalizedString
					/**
					 * Rozšíření PostgreSQL, které ukládá a indexuje vektorové embeddingy pro podobnostní vyhledávání.
					 */
					answer: () => LocalizedString
				}
				f4: {
					/**
					 * Co je RAG jednou větou?
					 */
					prompt: () => LocalizedString
					/**
					 * Vyhledejte relevantní chunky pomocí podobnostního hledání a vložte je do promptu před generováním.
					 */
					answer: () => LocalizedString
				}
				f5: {
					/**
					 * Jaký je kompromis mezi indexy ivfflat a hnsw?
					 */
					prompt: () => LocalizedString
					/**
					 * ivfflat: rychlejší sestavení, nižší recall; hnsw: pomalejší sestavení, vyšší recall a rychlejší dotazy.
					 */
					answer: () => LocalizedString
				}
				f6: {
					/**
					 * Proč samotná podobnost nemusí stačit?
					 */
					prompt: () => LocalizedString
					/**
					 * Retrieval může vrátit sémanticky blízké, ale kontextově špatné chunky; pomůže re-ranker nebo filtr.
					 */
					answer: () => LocalizedString
				}
			}
		}
		buildLabItems: {
			cursorFeatureSpike: {
				/**
				 * Cursor - prompt pro rychlý spike funkce
				 */
				title: () => LocalizedString
				/**
				 * Znovupoužitelný prompt pro vymezení a otestování nové funkce v repozitáři.
				 */
				summary: () => LocalizedString
				/**
				 * Pracuješ v <repo>. Chci udělat spike pro <feature>.
		
			Výstupy:
			1. Krátký návrh řešení (3-5 bodů).
			2. Minimální změny souborů potřebné pro funkční prototyp.
			3. Checklist navazujících kroků.
		
			Omezení: drž změny úzké, nepřejmenovávej soubory, přidej TODO tam, kde něco stubuješ.
				 */
				body: () => LocalizedString
			}
			cursorRefactorPrompt: {
				/**
				 * Cursor - prompt pro bezpečný refaktor
				 */
				title: () => LocalizedString
				/**
				 * Refaktor s mantinely: rozsah, testy a možnost návratu.
				 */
				summary: () => LocalizedString
				/**
				 * Refaktoruj <module> směrem k <goal>.
		
			Pravidla:
			- Žádné změny chování.
			- Co nejmenší diff.
			- Aktualizuj nebo přidej testy pro každou netriviální změnu.
			- Všechna rizika uveď na konci v sekci "Pozor".
				 */
				body: () => LocalizedString
			}
			chatbotLaunchPlaybook: {
				/**
				 * Spuštění interního chatbota - playbook
				 */
				title: () => LocalizedString
				/**
				 * Desetikrokový playbook od vymezení problému po spuštění v1.
				 */
				summary: () => LocalizedString
				/**
				 * ## 1. Problém
			Jakou bolest uživatelů odstraňujeme?
		
			## 2. Rozsah
			Co je uvnitř a co mimo?
		
			## 3. Data
			Jaký je korpus? Kde žije?
		
			## 4. Retrieval
			Nejdřív naivní RAG. Měřte.
		
			## 5. Prompt
			Systémový prompt + definice nástrojů.
		
			## 6. Evaluace
			Zlatá sada + rubrika.
		
			## 7. UI
			Štíhlé, bez ozdob.
		
			## 8. Guardraily
			PII, odmítnutí, zneužití.
		
			## 9. Telemetrie
			Logujte vstupy, výstupy a skóre.
		
			## 10. Spuštění
			Canary -> široké nasazení.
				 */
				body: () => LocalizedString
			}
			productPrdTemplate: {
				/**
				 * Šablona PRD pro AI funkci
				 */
				title: () => LocalizedString
				/**
				 * Malé PRD přizpůsobené AI funkcím: úkoly uživatelů, kritéria úspěchu, plán evaluací.
				 */
				summary: () => LocalizedString
				/**
				 * # <Název funkce>
		
			## Problém
			## Uživatelé a úkoly
			## Kritéria úspěchu
			## Náčrt řešení
			## Rizika
			## Plán evaluací
			## Otevřené otázky
				 */
				body: () => LocalizedString
			}
			shipChecklist: {
				/**
				 * Checklist pro nasazení AI funkce
				 */
				title: () => LocalizedString
				/**
				 * Kontroly před tím, než novou AI funkci pustíme reálným uživatelům.
				 */
				summary: () => LocalizedString
				/**
				 * - [ ] Systémový prompt zkontrolován
			- [ ] Schémata nástrojů validována
			- [ ] Existují evaluace promptů a retrievalu
			- [ ] Guardraily pro PII / zneužití jsou na místě
			- [ ] Nastaven cenový strop
			- [ ] Zapnuté logování a tracing
			- [ ] Plán rollout (canary -> široce)
			- [ ] Zdokumentovaný rollback plán
				 */
				body: () => LocalizedString
			}
		}
		canon: {
			attentionIsAllYouNeed: {
				/**
				 * Attention Is All You Need
				 */
				title: () => LocalizedString
				/**
				 * Původní článek představující architekturu Transformer. Základ moderních LLM.
				 */
				summary: () => LocalizedString
			}
			scalingLaws: {
				/**
				 * Scaling Laws for Neural Language Models
				 */
				title: () => LocalizedString
				/**
				 * OpenAI scaling laws: jak roste výkon modelu s velikostí dat, parametrů a výpočtu.
				 */
				summary: () => LocalizedString
			}
			chinchilla: {
				/**
				 * Chinchilla: Training Compute-Optimal LLMs
				 */
				title: () => LocalizedString
				/**
				 * DeepMind ukazuje, že většina LLM byla podtrénovaná na datech vůči svému výpočtu.
				 */
				summary: () => LocalizedString
			}
			bert: {
				/**
				 * BERT: Pre-training of Deep Bidirectional Transformers
				 */
				title: () => LocalizedString
				/**
				 * Encoder-only model, který popularizoval pre-training / fine-tuning paradigma.
				 */
				summary: () => LocalizedString
			}
			gpt3: {
				/**
				 * GPT-3: Language Models are Few-Shot Learners
				 */
				title: () => LocalizedString
				/**
				 * Článek, který ukázal, že škálování + in-context learning vede k emergentním schopnostem.
				 */
				summary: () => LocalizedString
			}
			llama: {
				/**
				 * LLaMA: Open and Efficient Foundation Language Models
				 */
				title: () => LocalizedString
				/**
				 * Meta uvolňuje silnou rodinu otevřených modelů a odstartuje open-source LLM ekosystém.
				 */
				summary: () => LocalizedString
			}
			mixtral: {
				/**
				 * Mixtral of Experts
				 */
				title: () => LocalizedString
				/**
				 * Mistral popisuje sparse mixture-of-experts model 8x7B s GPT-3.5 výkonem za zlomek nákladů.
				 */
				summary: () => LocalizedString
			}
			instructgpt: {
				/**
				 * InstructGPT: Training Language Models to Follow Instructions with Human Feedback
				 */
				title: () => LocalizedString
				/**
				 * Článek za ChatGPT: RLHF, který naučil GPT-3 plnit instrukce.
				 */
				summary: () => LocalizedString
			}
			constitutionalAi: {
				/**
				 * Constitutional AI: Harmlessness from AI Feedback
				 */
				title: () => LocalizedString
				/**
				 * Anthropic ukazuje RLAIF: AI hodnotí výstupy podle psaného souboru principů.
				 */
				summary: () => LocalizedString
			}
			dpo: {
				/**
				 * Direct Preference Optimization
				 */
				title: () => LocalizedString
				/**
				 * Trénink LLM podle preferenčních párů bez explicitního reward modelu — jednodušší než RLHF.
				 */
				summary: () => LocalizedString
			}
			cot: {
				/**
				 * Chain-of-Thought Prompting
				 */
				title: () => LocalizedString
				/**
				 * Ukazuje, jak prompty s mezikroky úvah zlepšují vícekrokové uvažování LLM.
				 */
				summary: () => LocalizedString
			}
			react: {
				/**
				 * ReAct: Synergizing Reasoning and Acting in Language Models
				 */
				title: () => LocalizedString
				/**
				 * Klasický agentní vzor: jazykový model střídá kroky uvažování a volání nástrojů.
				 */
				summary: () => LocalizedString
			}
			toolformer: {
				/**
				 * Toolformer: Language Models Can Teach Themselves to Use Tools
				 */
				title: () => LocalizedString
				/**
				 * Meta ukazuje, jak LLM samostatně získá schopnost volat externí API.
				 */
				summary: () => LocalizedString
			}
			rag: {
				/**
				 * Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
				 */
				title: () => LocalizedString
				/**
				 * Původní článek RAG: kombinace retrieve + generate pro úlohy nad znalostmi.
				 */
				summary: () => LocalizedString
			}
		}
	}
	home: {
		/**
		 * Vítejte
		 */
		eyebrow: () => LocalizedString
		/**
		 * AI Academy
		 */
		title: () => LocalizedString
		/**
		 * Malé interní hřiště pro to, jak se v AI zlepšit — společně. Vyberte si sekci nebo se podívejte, co tento týden vyšlo.
		 */
		description: () => LocalizedString
		/**
		 * Začít se učit
		 */
		startLearning: () => LocalizedString
		/**
		 * Otevřít Radar
		 */
		openRadar: () => LocalizedString
		/**
		 * Sekce
		 */
		sectionsHeading: () => LocalizedString
		/**
		 * Nejnovější témata
		 */
		latestTopics: () => LocalizedString
		/**
		 * Procházet vše
		 */
		browseAll: () => LocalizedString
		/**
		 * Z Radaru
		 */
		fromTheRadar: () => LocalizedString
	}
	learn: {
		/**
		 * Učení
		 */
		eyebrow: () => LocalizedString
		/**
		 * Mapa AI učení
		 */
		title: () => LocalizedString
		/**
		 * Krátká, vyhraněná cesta tématy, ve kterých by se měl orientovat každý interní tým. Vyberte si trasu nebo skočte rovnou do libovolného tématu.
		 */
		description: () => LocalizedString
		/**
		 * Trasy
		 */
		statTracks: () => LocalizedString
		/**
		 * Témata
		 */
		statTopics: () => LocalizedString
		/**
		 * Odhadované čtení
		 */
		statEstimatedReading: () => LocalizedString
		/**
		 * Trasa
		 */
		trackEyebrow: () => LocalizedString
		/**
		 * odvozeno
		 */
		trackDerived: () => LocalizedString
		/**
		 * {count|num} {{téma|témata|témat}}
		 */
		topicsCount: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Nezařazená témata
		 */
		uncategorisedTitle: () => LocalizedString
		/**
		 * Témata, která zatím nejsou napojena na žádnou trasu.
		 */
		uncategorisedDescription: () => LocalizedString
		/**
		 * Trasa {n|num}
		 */
		derivedTrackTitle: (arg: { n: unknown }) => LocalizedString
		/**
		 * Metadata trasy nejsou k dispozici — zobrazují se témata podle uloženého ID trasy.
		 */
		derivedTrackDescription: () => LocalizedString
		/**
		 * Otevřít téma
		 */
		openTopic: () => LocalizedString
		/**
		 * {count|num} min
		 */
		topicMinutes: (arg: { count: unknown }) => LocalizedString
	}
	library: {
		/**
		 * Knihovna
		 */
		eyebrow: () => LocalizedString
		/**
		 * Vaše uložené zdroje a poznámky
		 */
		title: () => LocalizedString
		/**
		 * Vše, co jste si uložili z Radaru a Učení, plus vaše osobní poznámky.
		 */
		description: () => LocalizedString
		/**
		 * Uložené
		 */
		tabSaved: () => LocalizedString
		/**
		 * Poznámky
		 */
		tabNotes: () => LocalizedString
		/**
		 * Kánon
		 */
		tabCanon: () => LocalizedString
		/**
		 * Knihovna je zatím prázdná
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Uložte si zdroje z Radaru nebo Učení — najdete je tady.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Zatím žádné poznámky
		 */
		notesEmptyTitle: () => LocalizedString
		/**
		 * Vytvořte si poznámku k tématu nebo zdroji.
		 */
		notesEmptyDescription: () => LocalizedString
		/**
		 * Kánon
		 */
		canonEyebrow: () => LocalizedString
		/**
		 * Základní práce, které stojí za to znát
		 */
		canonTitle: () => LocalizedString
		/**
		 * Ručně vybraný seznam zakládajících článků a publikací o AI seskupený podle tématu.
		 */
		canonDescription: () => LocalizedString
		/**
		 * Kánon je zatím prázdný
		 */
		canonEmptyTitle: () => LocalizedString
		/**
		 * Až přidáme základní práce, objeví se zde.
		 */
		canonEmptyDescription: () => LocalizedString
		/**
		 * Základy
		 */
		canonCategoryFoundations: () => LocalizedString
		/**
		 * Modely
		 */
		canonCategoryModels: () => LocalizedString
		/**
		 * Alignment a RLHF
		 */
		canonCategoryAlignment: () => LocalizedString
		/**
		 * Prompting a uvažování
		 */
		canonCategoryPrompting: () => LocalizedString
		/**
		 * Agenti a nástroje
		 */
		canonCategoryAgents: () => LocalizedString
		/**
		 * RAG a vyhledávání
		 */
		canonCategoryRag: () => LocalizedString
		/**
		 * Škálování
		 */
		canonCategoryScaling: () => LocalizedString
		/**
		 * Multimodalita
		 */
		canonCategoryMultimodal: () => LocalizedString
		/**
		 * Uvažování
		 */
		canonCategoryReasoning: () => LocalizedString
		/**
		 * Ostatní
		 */
		canonCategoryOther: () => LocalizedString
		/**
		 * Hledat v akademické literatuře
		 */
		searchCardTitle: () => LocalizedString
		/**
		 * Najděte si svůj přesný dotaz napříč Semantic Scholar, OpenAlex a arXiv. Uložení jedním klikem.
		 */
		searchCardDescription: () => LocalizedString
		/**
		 * Otevřít vyhledávání
		 */
		searchCardCta: () => LocalizedString
	}
	nav: {
		/**
		 * Domů
		 */
		homeLink: () => LocalizedString
		/**
		 * Učení
		 */
		learnLink: () => LocalizedString
		/**
		 * Mapa AI
		 */
		mapLink: () => LocalizedString
		/**
		 * Radar
		 */
		radarLink: () => LocalizedString
		/**
		 * Knihovna
		 */
		libraryLink: () => LocalizedString
		/**
		 * Procvičování
		 */
		practiceLink: () => LocalizedString
		/**
		 * Build Lab
		 */
		buildLabLink: () => LocalizedString
		/**
		 * Rozbalit panel
		 */
		expandSidebar: () => LocalizedString
		/**
		 * Sbalit panel
		 */
		collapseSidebar: () => LocalizedString
	}
	paperSearch: {
		/**
		 * Vyhledávání publikací
		 */
		eyebrow: () => LocalizedString
		/**
		 * Hledejte odbornou literaturu
		 */
		title: () => LocalizedString
		/**
		 * Spojuje výsledky ze Semantic Scholar, OpenAlex a arXiv a deduplikuje je podle DOI a arXiv ID.
		 */
		description: () => LocalizedString
		/**
		 * např. „chain of thought prompting“ nebo „direct preference optimization“
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Hledat
		 */
		searchAction: () => LocalizedString
		/**
		 * Hledám…
		 */
		searching: () => LocalizedString
		/**
		 * Filtry
		 */
		filtersTitle: () => LocalizedString
		/**
		 * Od roku
		 */
		yearMinLabel: () => LocalizedString
		/**
		 * Do roku
		 */
		yearMaxLabel: () => LocalizedString
		/**
		 * Min. citací
		 */
		minCitationsLabel: () => LocalizedString
		/**
		 * Řadit
		 */
		sortLabel: () => LocalizedString
		/**
		 * Relevance
		 */
		sortRelevance: () => LocalizedString
		/**
		 * Nejvíc citované
		 */
		sortCitations: () => LocalizedString
		/**
		 * Nejnovější
		 */
		sortYear: () => LocalizedString
		/**
		 * Vymazat filtry
		 */
		reset: () => LocalizedString
		/**
		 * Výsledků: {count|num}
		 */
		resultsHeader: (arg: { count: unknown }) => LocalizedString
		/**
		 * Žádné výsledky
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Zkuste obecnější dotaz nebo uvolněte filtry.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Začněte psát dotaz
		 */
		startTitle: () => LocalizedString
		/**
		 * Můžete vyhledávat klíčová slova, fráze, autory nebo název práce.
		 */
		startDescription: () => LocalizedString
		/**
		 * Některé zdroje selhaly: {sources}
		 */
		upstreamWarning: (arg: { sources: unknown }) => LocalizedString
		/**
		 * {count|num} {{citace|citace|citací}}
		 */
		citationsLabel: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * {year|num}
		 */
		yearLabel: (arg: { year: unknown }) => LocalizedString
		/**
		 * PDF
		 */
		pdfLabel: () => LocalizedString
		/**
		 * Zdroj
		 */
		sourceLabel: () => LocalizedString
		/**
		 * Uložit
		 */
		saveAction: () => LocalizedString
		/**
		 * Uloženo
		 */
		savedAction: () => LocalizedString
		/**
		 * Uložení selhalo
		 */
		saveFailed: () => LocalizedString
		/**
		 * Uloženo do Knihovny
		 */
		savedToast: () => LocalizedString
	}
	practice: {
		/**
		 * Procvičování
		 */
		eyebrow: () => LocalizedString
		/**
		 * Kvízy a kartičky
		 */
		title: () => LocalizedString
		/**
		 * Krátké kvízy generované z témat. Začněte předpřipraveným kvízem nebo si nechte vygenerovat nový.
		 */
		description: () => LocalizedString
		/**
		 * Spustit kvíz
		 */
		startQuiz: () => LocalizedString
		/**
		 * Start
		 */
		start: () => LocalizedString
		/**
		 * Zatím žádné kvízy
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Tématům zatím nebyly přiřazeny žádné kvízy.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Téma
		 */
		topicLabel: () => LocalizedString
		/**
		 * {count|num} {{otázka|otázky|otázek}}
		 */
		questionCount: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * {count|num} {{výběrová otázka|výběrové otázky|výběrových otázek}}
		 */
		mcqCount: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * {count|num} {{kartička|kartičky|kartiček}}
		 */
		flashcardCount: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Kvíz nenalezen
		 */
		quizNotFoundTitle: () => LocalizedString
		/**
		 * Možná byl odstraněn nebo ještě není publikovaný.
		 */
		quizNotFoundDescription: () => LocalizedString
		/**
		 * Zpět na procvičování
		 */
		backToPractice: () => LocalizedString
		/**
		 * Otázka {current|num} z {total|num}
		 */
		questionProgress: (arg: { current: unknown, total: unknown }) => LocalizedString
		/**
		 * Předchozí
		 */
		previous: () => LocalizedString
		/**
		 * Další
		 */
		next: () => LocalizedString
		/**
		 * Dokončit
		 */
		finish: () => LocalizedString
		/**
		 * Ukázat odpověď
		 */
		showAnswer: () => LocalizedString
		/**
		 * Jak vám to šlo?
		 */
		selfRatePrompt: () => LocalizedString
		/**
		 * Nevěděl/a jsem
		 */
		missedIt: () => LocalizedString
		/**
		 * Věděl/a jsem
		 */
		gotIt: () => LocalizedString
		/**
		 * Skvělá práce
		 */
		niceWork: () => LocalizedString
		/**
		 * Dobrý pokus
		 */
		goodAttempt: () => LocalizedString
		/**
		 * Vaše skóre: {score|num} z {total|num}.
		 */
		scoreSummary: (arg: { score: unknown, total: unknown }) => LocalizedString
		/**
		 * Zkusit znovu
		 */
		tryAgain: () => LocalizedString
		/**
		 * Procvičování s AI
		 */
		aiCardTitle: () => LocalizedString
		/**
		 * Vygenerujte nové otázky k tomuto tématu na vyžádání.
		 */
		aiCardDescription: () => LocalizedString
		/**
		 * Generovat
		 */
		generate: () => LocalizedString
		/**
		 * Vygenerovat znovu
		 */
		regenerate: () => LocalizedString
		/**
		 * Generuji…
		 */
		generating: () => LocalizedString
		/**
		 * Generování selhalo
		 */
		generationFailed: () => LocalizedString
		/**
		 * Vygenerováno {count|num} {{otázka|otázky|otázek}}
		 */
		generatedToast: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Otázka {n|num}
		 */
		questionLabel: (arg: { n: unknown }) => LocalizedString
		/**
		 * Výběr
		 */
		questionKindMcq: () => LocalizedString
		/**
		 * Kartička
		 */
		questionKindFlashcard: () => LocalizedString
		/**
		 * Odpověď:
		 */
		answerLabel: () => LocalizedString
	}
	radar: {
		/**
		 * Radar
		 */
		eyebrow: () => LocalizedString
		/**
		 * Co je nového v AI
		 */
		title: () => LocalizedString
		/**
		 * Souhrn článků, novinek a vědeckých prací z našich důvěryhodných zdrojů.
		 */
		description: () => LocalizedString
		/**
		 * Zatím nic nového
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Až dorazí čerstvé položky, objeví se zde.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Nepodařilo se načíst Radar
		 */
		errorTitle: () => LocalizedString
		/**
		 * Hledat v titulku, popisu, štítcích…
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Obnovit
		 */
		refresh: () => LocalizedString
		/**
		 * Doporučené
		 */
		sortRecommended: () => LocalizedString
		/**
		 * Nejnovější
		 */
		sortRecent: () => LocalizedString
		/**
		 * Vše
		 */
		tabAll: () => LocalizedString
		/**
		 * Práce
		 */
		tabPapers: () => LocalizedString
		/**
		 * Vydání
		 */
		tabReleases: () => LocalizedString
		/**
		 * Blogy
		 */
		tabBlogs: () => LocalizedString
		/**
		 * Komunita
		 */
		tabCommunity: () => LocalizedString
		/**
		 * Nástroje
		 */
		tabTools: () => LocalizedString
		/**
		 * {count|num} {{hlas|hlasy|hlasů}} na HF
		 */
		upvotesLabel: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * ID: {id}
		 */
		externalIdLabel: (arg: { id: unknown }) => LocalizedString
		/**
		 * Skóre: {score}
		 */
		scoreLabel: (arg: { score: unknown }) => LocalizedString
		/**
		 * Uloženo do Knihovny
		 */
		savedToast: () => LocalizedString
		/**
		 * Odebráno z Knihovny
		 */
		removedToast: () => LocalizedString
		/**
		 * Uložení selhalo
		 */
		saveFailed: () => LocalizedString
		/**
		 * Uložit do Knihovny
		 */
		saveAction: () => LocalizedString
		/**
		 * Odebrat z Knihovny
		 */
		unsaveAction: () => LocalizedString
		/**
		 * Otevřít zdroj
		 */
		openExternal: () => LocalizedString
	}
	reader: {
		/**
		 * Čtenář
		 */
		eyebrow: () => LocalizedString
		/**
		 * Číst v AI Academy
		 */
		openInternal: () => LocalizedString
		/**
		 * Původní zdroj
		 */
		openOriginal: () => LocalizedString
		/**
		 * Otevřít původní zdroj v novém okně
		 */
		openOriginalAria: () => LocalizedString
		/**
		 * Zpět
		 */
		back: () => LocalizedString
		/**
		 * Zdroj: {name}
		 */
		sourceLabel: (arg: { name: unknown }) => LocalizedString
		/**
		 * Publikováno {date}
		 */
		publishedLabel: (arg: { date: unknown }) => LocalizedString
		/**
		 * Autor: {author}
		 */
		authorLabel: (arg: { author: unknown }) => LocalizedString
		/**
		 * Licence: {license}
		 */
		licenseLabel: (arg: { license: unknown }) => LocalizedString
		/**
		 * Přeložit do {locale}
		 */
		translateAction: (arg: { locale: unknown }) => LocalizedString
		/**
		 * Překládám…
		 */
		translatingNow: () => LocalizedString
		/**
		 * Překlad se nezdařil
		 */
		translateFailed: () => LocalizedString
		/**
		 * Přeložil {provider}
		 */
		translatedBy: (arg: { provider: unknown }) => LocalizedString
		/**
		 * Přeloženo z jazyka {sourceLang}
		 */
		translatedFromSource: (arg: { sourceLang: unknown }) => LocalizedString
		/**
		 * Zobrazit původní jazyk
		 */
		showSource: () => LocalizedString
		/**
		 * Načítám článek…
		 */
		loading: () => LocalizedString
		/**
		 * Tento článek ještě není připraven ke čtení
		 */
		notReadyTitle: () => LocalizedString
		/**
		 * Pracujeme na jeho importu. Mezitím můžete otevřít původní zdroj.
		 */
		notReadyDescription: () => LocalizedString
		/**
		 * Nepodařilo se importovat článek
		 */
		importFailedTitle: () => LocalizedString
		/**
		 * Zkusíme to znovu později. Původní zdroj je stále dostupný.
		 */
		importFailedDescription: () => LocalizedString
		/**
		 * Článek nebyl nalezen
		 */
		notFoundTitle: () => LocalizedString
		/**
		 * Zdroj mohl být odstraněn.
		 */
		notFoundDescription: () => LocalizedString
		/**
		 * Pouze metadata
		 */
		availabilityMetadataOnly: () => LocalizedString
		/**
		 * Pouze úryvek
		 */
		availabilityExcerptOnly: () => LocalizedString
		/**
		 * Plný text není dostupný
		 */
		availabilityUnavailable: () => LocalizedString
	}
	userMenu: {
		/**
		 * Nabídka uživatele
		 */
		trigger: () => LocalizedString
		/**
		 * Vzhled
		 */
		appearance: () => LocalizedString
		/**
		 * Motiv
		 */
		theme: () => LocalizedString
		/**
		 * Světlý
		 */
		themeLight: () => LocalizedString
		/**
		 * Tmavý
		 */
		themeDark: () => LocalizedString
		/**
		 * Systém
		 */
		themeSystem: () => LocalizedString
		/**
		 * Jazyk
		 */
		language: () => LocalizedString
		/**
		 * Kopírovat e-mail
		 */
		copyEmail: () => LocalizedString
		/**
		 * E-mail zkopírován
		 */
		copiedEmail: () => LocalizedString
		/**
		 * E-mail se nepodařilo zkopírovat
		 */
		copyEmailFailed: () => LocalizedString
		/**
		 * Klávesové zkratky
		 */
		keyboardShortcuts: () => LocalizedString
		/**
		 * Klávesové zkratky brzy
		 */
		keyboardShortcutsToast: () => LocalizedString
		/**
		 * Po zprovoznění bude „/“ zaměřovat vyhledávání.
		 */
		keyboardShortcutsHint: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		signOut: () => LocalizedString
		/**
		 * Odhlášeno
		 */
		signedOut: () => LocalizedString
		/**
		 * Odhlášení selhalo
		 */
		signOutFailed: () => LocalizedString
		/**
		 * Demo režim
		 */
		demoModeTitle: () => LocalizedString
		/**
		 * Pro přihlášení nakonfigurujte Supabase.
		 */
		demoModeDescription: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		signIn: () => LocalizedString
	}
}

export type Formatters = {
	num: (value: unknown | string | number | boolean) => unknown
}
