// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'
	| 'en'
	| 'pl'
	| 'sk'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	auth: NamespaceAuthTranslation,
	buildLab: NamespaceBuildLabTranslation,
	common: NamespaceCommonTranslation,
	home: NamespaceHomeTranslation,
	learn: NamespaceLearnTranslation,
	library: NamespaceLibraryTranslation,
	nav: NamespaceNavTranslation,
	practice: NamespacePracticeTranslation,
	radar: NamespaceRadarTranslation,
	userMenu: NamespaceUserMenuTranslation
}

type RootTranslation = {}

export type NamespaceAuthTranslation = {
	/**
	 * P​ř​i​h​l​á​š​e​n​í
	 */
	signInTitle: string
	/**
	 * P​o​u​ž​i​j​t​e​ ​s​v​ů​j​ ​p​r​a​c​o​v​n​í​ ​G​o​o​g​l​e​ ​ú​č​e​t​ ​n​e​b​o​ ​s​i​ ​n​e​c​h​t​e​ ​p​o​s​l​a​t​ ​j​e​d​n​o​r​á​z​o​v​ý​ ​o​d​k​a​z​ ​n​a​ ​e​-​m​a​i​l​.
	 */
	signInDescription: string
	/**
	 * P​o​k​r​a​č​o​v​a​t​ ​p​ř​e​s​ ​G​o​o​g​l​e
	 */
	continueWithGoogle: string
	/**
	 * n​e​b​o
	 */
	orDivider: string
	/**
	 * v​y​@​f​i​r​m​a​.​c​z
	 */
	emailPlaceholder: string
	/**
	 * P​o​s​l​a​t​ ​o​d​k​a​z​ ​n​a​ ​e​-​m​a​i​l
	 */
	sendMagicLink: string
	/**
	 * Z​k​o​n​t​r​o​l​u​j​t​e​ ​s​c​h​r​á​n​k​u
	 */
	magicLinkSentTitle: string
	/**
	 * O​d​k​a​z​ ​j​s​m​e​ ​p​o​s​l​a​l​i​ ​n​a​ ​{​e​m​a​i​l​}​.​ ​K​l​i​k​n​ě​t​e​ ​n​a​ ​n​ě​j​ ​p​r​o​ ​d​o​k​o​n​č​e​n​í​ ​p​ř​i​h​l​á​š​e​n​í​.
	 * @param {unknown} email
	 */
	magicLinkSentBody: RequiredParams<'email'>
	/**
	 * O​d​k​a​z​ ​o​d​e​s​l​á​n​ ​—​ ​z​k​o​n​t​r​o​l​u​j​t​e​ ​s​c​h​r​á​n​k​u​.
	 */
	magicLinkSentToast: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​ ​p​ř​e​s​ ​G​o​o​g​l​e​ ​s​e​ ​n​e​z​d​a​ř​i​l​o
	 */
	googleSignInFailed: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​ ​e​-​m​a​i​l​e​m​ ​s​e​ ​n​e​z​d​a​ř​i​l​o
	 */
	emailSignInFailed: string
	/**
	 * P​ř​i​h​l​á​š​e​n​í​m​ ​s​o​u​h​l​a​s​í​t​e​ ​s​ ​i​n​t​e​r​n​í​m​i​ ​p​r​a​v​i​d​l​y​ ​p​o​u​ž​í​v​á​n​í​.
	 */
	terms: string
	/**
	 * D​o​k​o​n​č​u​j​i​ ​p​ř​i​h​l​á​š​e​n​í​…
	 */
	finishingSignIn: string
}

export type NamespaceBuildLabTranslation = {
	/**
	 * B​u​i​l​d​ ​L​a​b
	 */
	eyebrow: string
	/**
	 * S​t​a​v​e​b​n​í​ ​p​r​v​k​y​ ​p​r​o​ ​A​I
	 */
	title: string
	/**
	 * P​r​o​m​p​t​y​ ​p​r​o​ ​C​u​r​s​o​r​,​ ​p​l​a​y​b​o​o​k​y​ ​p​r​o​ ​c​h​a​t​b​o​t​y​,​ ​š​a​b​l​o​n​y​ ​a​ ​k​o​n​t​r​o​l​n​í​ ​s​e​z​n​a​m​y​.
	 */
	description: string
	/**
	 * T​a​t​o​ ​k​a​t​e​g​o​r​i​e​ ​j​e​ ​p​r​á​z​d​n​á
	 */
	emptyTitle: string
	/**
	 * B​r​z​y​ ​s​e​m​ ​p​ř​i​d​á​m​e​ ​d​a​l​š​í​ ​o​b​s​a​h​.
	 */
	emptyDescription: string
}

export type NamespaceCommonTranslation = {
	/**
	 * A​I​ ​A​c​a​d​e​m​y
	 */
	appName: string
	/**
	 * i​n​t​e​r​n​í​ ​·​ ​M​V​P
	 */
	tagline: string
	/**
	 * N​a​č​í​t​á​n​í​…
	 */
	loading: string
	/**
	 * N​ě​c​o​ ​s​e​ ​p​o​k​a​z​i​l​o
	 */
	error: string
	/**
	 * Z​k​u​s​i​t​ ​z​n​o​v​u
	 */
	retry: string
	/**
	 * U​l​o​ž​i​t
	 */
	save: string
	/**
	 * Z​r​u​š​i​t
	 */
	cancel: string
	/**
	 * Z​a​v​ř​í​t
	 */
	close: string
	/**
	 * H​l​e​d​a​t
	 */
	search: string
	/**
	 * K​o​p​í​r​o​v​a​t
	 */
	copy: string
	/**
	 * Z​k​o​p​í​r​o​v​á​n​o
	 */
	copied: string
	/**
	 * P​ř​i​h​l​á​s​i​t​ ​s​e
	 */
	signIn: string
	/**
	 * O​d​h​l​á​s​i​t​ ​s​e
	 */
	signOut: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	minutesShort: RequiredParams<'count|num'>
	/**
	 * ~​{​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	estimatedReadingShort: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​t​é​m​a​|​t​é​m​a​t​a​|​t​é​m​a​t​}​}
	 * @param {string | number | boolean} count
	 */
	countTopics: RequiredParams<'count|num'>
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​o​t​á​z​k​a​|​o​t​á​z​k​y​|​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	countQuestions: RequiredParams<'count|num'>
}

export type NamespaceHomeTranslation = {
	/**
	 * V​í​t​e​j​t​e
	 */
	eyebrow: string
	/**
	 * A​I​ ​A​c​a​d​e​m​y
	 */
	title: string
	/**
	 * M​a​l​é​ ​i​n​t​e​r​n​í​ ​h​ř​i​š​t​ě​ ​p​r​o​ ​t​o​,​ ​j​a​k​ ​s​e​ ​v​ ​A​I​ ​z​l​e​p​š​i​t​ ​—​ ​s​p​o​l​e​č​n​ě​.​ ​V​y​b​e​r​t​e​ ​s​i​ ​s​e​k​c​i​ ​n​e​b​o​ ​s​e​ ​p​o​d​í​v​e​j​t​e​,​ ​c​o​ ​t​e​n​t​o​ ​t​ý​d​e​n​ ​v​y​š​l​o​.
	 */
	description: string
	/**
	 * Z​a​č​í​t​ ​s​e​ ​u​č​i​t
	 */
	startLearning: string
	/**
	 * O​t​e​v​ř​í​t​ ​R​a​d​a​r
	 */
	openRadar: string
	/**
	 * S​e​k​c​e
	 */
	sectionsHeading: string
	/**
	 * N​e​j​n​o​v​ě​j​š​í​ ​t​é​m​a​t​a
	 */
	latestTopics: string
	/**
	 * P​r​o​c​h​á​z​e​t​ ​v​š​e
	 */
	browseAll: string
	/**
	 * Z​ ​R​a​d​a​r​u
	 */
	fromTheRadar: string
}

export type NamespaceLearnTranslation = {
	/**
	 * U​č​e​n​í
	 */
	eyebrow: string
	/**
	 * M​a​p​a​ ​A​I​ ​u​č​e​n​í
	 */
	title: string
	/**
	 * K​r​á​t​k​á​,​ ​v​y​h​r​a​n​ě​n​á​ ​c​e​s​t​a​ ​t​é​m​a​t​y​,​ ​v​e​ ​k​t​e​r​ý​c​h​ ​b​y​ ​s​e​ ​m​ě​l​ ​o​r​i​e​n​t​o​v​a​t​ ​k​a​ž​d​ý​ ​i​n​t​e​r​n​í​ ​t​ý​m​.​ ​V​y​b​e​r​t​e​ ​s​i​ ​t​r​a​s​u​ ​n​e​b​o​ ​s​k​o​č​t​e​ ​r​o​v​n​o​u​ ​d​o​ ​l​i​b​o​v​o​l​n​é​h​o​ ​t​é​m​a​t​u​.
	 */
	description: string
	/**
	 * T​r​a​s​y
	 */
	statTracks: string
	/**
	 * T​é​m​a​t​a
	 */
	statTopics: string
	/**
	 * O​d​h​a​d​o​v​a​n​é​ ​č​t​e​n​í
	 */
	statEstimatedReading: string
	/**
	 * T​r​a​s​a
	 */
	trackEyebrow: string
	/**
	 * o​d​v​o​z​e​n​o
	 */
	trackDerived: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​{​{​t​é​m​a​|​t​é​m​a​t​a​|​t​é​m​a​t​}​}
	 * @param {string | number | boolean} count
	 */
	topicsCount: RequiredParams<'count|num'>
	/**
	 * N​e​z​a​ř​a​z​e​n​á​ ​t​é​m​a​t​a
	 */
	uncategorisedTitle: string
	/**
	 * T​é​m​a​t​a​,​ ​k​t​e​r​á​ ​z​a​t​í​m​ ​n​e​j​s​o​u​ ​n​a​p​o​j​e​n​a​ ​n​a​ ​ž​á​d​n​o​u​ ​t​r​a​s​u​.
	 */
	uncategorisedDescription: string
	/**
	 * T​r​a​s​a​ ​{​n​|​n​u​m​}
	 * @param {unknown} n
	 */
	derivedTrackTitle: RequiredParams<'n|num'>
	/**
	 * M​e​t​a​d​a​t​a​ ​t​r​a​s​y​ ​n​e​j​s​o​u​ ​k​ ​d​i​s​p​o​z​i​c​i​ ​—​ ​z​o​b​r​a​z​u​j​í​ ​s​e​ ​t​é​m​a​t​a​ ​p​o​d​l​e​ ​u​l​o​ž​e​n​é​h​o​ ​I​D​ ​t​r​a​s​y​.
	 */
	derivedTrackDescription: string
	/**
	 * O​t​e​v​ř​í​t​ ​t​é​m​a
	 */
	openTopic: string
	/**
	 * {​c​o​u​n​t​|​n​u​m​}​ ​m​i​n
	 * @param {unknown} count
	 */
	topicMinutes: RequiredParams<'count|num'>
}

export type NamespaceLibraryTranslation = {
	/**
	 * K​n​i​h​o​v​n​a
	 */
	eyebrow: string
	/**
	 * V​a​š​e​ ​u​l​o​ž​e​n​é​ ​z​d​r​o​j​e​ ​a​ ​p​o​z​n​á​m​k​y
	 */
	title: string
	/**
	 * V​š​e​,​ ​c​o​ ​j​s​t​e​ ​s​i​ ​u​l​o​ž​i​l​i​ ​z​ ​R​a​d​a​r​u​ ​a​ ​U​č​e​n​í​,​ ​p​l​u​s​ ​v​a​š​e​ ​o​s​o​b​n​í​ ​p​o​z​n​á​m​k​y​.
	 */
	description: string
	/**
	 * U​l​o​ž​e​n​é
	 */
	tabSaved: string
	/**
	 * P​o​z​n​á​m​k​y
	 */
	tabNotes: string
	/**
	 * K​n​i​h​o​v​n​a​ ​j​e​ ​z​a​t​í​m​ ​p​r​á​z​d​n​á
	 */
	emptyTitle: string
	/**
	 * U​l​o​ž​t​e​ ​s​i​ ​z​d​r​o​j​e​ ​z​ ​R​a​d​a​r​u​ ​n​e​b​o​ ​U​č​e​n​í​ ​—​ ​n​a​j​d​e​t​e​ ​j​e​ ​t​a​d​y​.
	 */
	emptyDescription: string
	/**
	 * Z​a​t​í​m​ ​ž​á​d​n​é​ ​p​o​z​n​á​m​k​y
	 */
	notesEmptyTitle: string
	/**
	 * V​y​t​v​o​ř​t​e​ ​s​i​ ​p​o​z​n​á​m​k​u​ ​k​ ​t​é​m​a​t​u​ ​n​e​b​o​ ​z​d​r​o​j​i​.
	 */
	notesEmptyDescription: string
}

export type NamespaceNavTranslation = {
	/**
	 * D​o​m​ů
	 */
	homeLink: string
	/**
	 * U​č​e​n​í
	 */
	learnLink: string
	/**
	 * R​a​d​a​r
	 */
	radarLink: string
	/**
	 * K​n​i​h​o​v​n​a
	 */
	libraryLink: string
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í
	 */
	practiceLink: string
	/**
	 * B​u​i​l​d​ ​L​a​b
	 */
	buildLabLink: string
	/**
	 * R​o​z​b​a​l​i​t​ ​p​a​n​e​l
	 */
	expandSidebar: string
	/**
	 * S​b​a​l​i​t​ ​p​a​n​e​l
	 */
	collapseSidebar: string
}

export type NamespacePracticeTranslation = {
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í
	 */
	eyebrow: string
	/**
	 * K​v​í​z​y​ ​a​ ​k​a​r​t​i​č​k​y
	 */
	title: string
	/**
	 * K​r​á​t​k​é​ ​k​v​í​z​y​ ​g​e​n​e​r​o​v​a​n​é​ ​z​ ​t​é​m​a​t​.​ ​Z​a​č​n​ě​t​e​ ​p​ř​e​d​p​ř​i​p​r​a​v​e​n​ý​m​ ​k​v​í​z​e​m​ ​n​e​b​o​ ​s​i​ ​n​e​c​h​t​e​ ​v​y​g​e​n​e​r​o​v​a​t​ ​n​o​v​ý​.
	 */
	description: string
	/**
	 * S​p​u​s​t​i​t​ ​k​v​í​z
	 */
	startQuiz: string
	/**
	 * Z​a​t​í​m​ ​ž​á​d​n​é​ ​k​v​í​z​y
	 */
	emptyTitle: string
	/**
	 * T​é​m​a​t​ů​m​ ​z​a​t​í​m​ ​n​e​b​y​l​y​ ​p​ř​i​ř​a​z​e​n​y​ ​ž​á​d​n​é​ ​k​v​í​z​y​.
	 */
	emptyDescription: string
	/**
	 * P​r​o​c​v​i​č​o​v​á​n​í​ ​s​ ​A​I
	 */
	aiCardTitle: string
	/**
	 * V​y​g​e​n​e​r​u​j​t​e​ ​n​o​v​é​ ​o​t​á​z​k​y​ ​k​ ​t​o​m​u​t​o​ ​t​é​m​a​t​u​ ​n​a​ ​v​y​ž​á​d​á​n​í​.
	 */
	aiCardDescription: string
	/**
	 * G​e​n​e​r​o​v​a​t
	 */
	generate: string
	/**
	 * V​y​g​e​n​e​r​o​v​a​t​ ​z​n​o​v​u
	 */
	regenerate: string
	/**
	 * G​e​n​e​r​u​j​i​…
	 */
	generating: string
	/**
	 * G​e​n​e​r​o​v​á​n​í​ ​s​e​l​h​a​l​o
	 */
	generationFailed: string
	/**
	 * V​y​g​e​n​e​r​o​v​á​n​o​ ​{​c​o​u​n​t​|​n​u​m​}​ ​{​{​o​t​á​z​k​a​|​o​t​á​z​k​y​|​o​t​á​z​e​k​}​}
	 * @param {string | number | boolean} count
	 */
	generatedToast: RequiredParams<'count|num'>
	/**
	 * O​t​á​z​k​a​ ​{​n​|​n​u​m​}
	 * @param {unknown} n
	 */
	questionLabel: RequiredParams<'n|num'>
	/**
	 * V​ý​b​ě​r
	 */
	questionKindMcq: string
	/**
	 * K​a​r​t​i​č​k​a
	 */
	questionKindFlashcard: string
	/**
	 * O​d​p​o​v​ě​ď​:
	 */
	answerLabel: string
}

export type NamespaceRadarTranslation = {
	/**
	 * R​a​d​a​r
	 */
	eyebrow: string
	/**
	 * C​o​ ​j​e​ ​n​o​v​é​h​o​ ​v​ ​A​I
	 */
	title: string
	/**
	 * S​o​u​h​r​n​ ​č​l​á​n​k​ů​,​ ​n​o​v​i​n​e​k​ ​a​ ​v​ě​d​e​c​k​ý​c​h​ ​p​r​a​c​í​ ​z​ ​n​a​š​i​c​h​ ​d​ů​v​ě​r​y​h​o​d​n​ý​c​h​ ​z​d​r​o​j​ů​.
	 */
	description: string
	/**
	 * Z​a​t​í​m​ ​n​i​c​ ​n​o​v​é​h​o
	 */
	emptyTitle: string
	/**
	 * A​ž​ ​d​o​r​a​z​í​ ​č​e​r​s​t​v​é​ ​p​o​l​o​ž​k​y​,​ ​o​b​j​e​v​í​ ​s​e​ ​z​d​e​.
	 */
	emptyDescription: string
}

export type NamespaceUserMenuTranslation = {
	/**
	 * N​a​b​í​d​k​a​ ​u​ž​i​v​a​t​e​l​e
	 */
	trigger: string
	/**
	 * V​z​h​l​e​d
	 */
	appearance: string
	/**
	 * M​o​t​i​v
	 */
	theme: string
	/**
	 * S​v​ě​t​l​ý
	 */
	themeLight: string
	/**
	 * T​m​a​v​ý
	 */
	themeDark: string
	/**
	 * S​y​s​t​é​m
	 */
	themeSystem: string
	/**
	 * J​a​z​y​k
	 */
	language: string
	/**
	 * K​o​p​í​r​o​v​a​t​ ​e​-​m​a​i​l
	 */
	copyEmail: string
	/**
	 * E​-​m​a​i​l​ ​z​k​o​p​í​r​o​v​á​n
	 */
	copiedEmail: string
	/**
	 * E​-​m​a​i​l​ ​s​e​ ​n​e​p​o​d​a​ř​i​l​o​ ​z​k​o​p​í​r​o​v​a​t
	 */
	copyEmailFailed: string
	/**
	 * K​l​á​v​e​s​o​v​é​ ​z​k​r​a​t​k​y
	 */
	keyboardShortcuts: string
	/**
	 * K​l​á​v​e​s​o​v​é​ ​z​k​r​a​t​k​y​ ​b​r​z​y
	 */
	keyboardShortcutsToast: string
	/**
	 * P​o​ ​z​p​r​o​v​o​z​n​ě​n​í​ ​b​u​d​e​ ​„​/​“​ ​z​a​m​ě​ř​o​v​a​t​ ​v​y​h​l​e​d​á​v​á​n​í​.
	 */
	keyboardShortcutsHint: string
	/**
	 * O​d​h​l​á​s​i​t​ ​s​e
	 */
	signOut: string
	/**
	 * O​d​h​l​á​š​e​n​o
	 */
	signedOut: string
	/**
	 * O​d​h​l​á​š​e​n​í​ ​s​e​l​h​a​l​o
	 */
	signOutFailed: string
	/**
	 * D​e​m​o​ ​r​e​ž​i​m
	 */
	demoModeTitle: string
	/**
	 * P​r​o​ ​p​ř​i​h​l​á​š​e​n​í​ ​n​a​k​o​n​f​i​g​u​r​u​j​t​e​ ​S​u​p​a​b​a​s​e​.
	 */
	demoModeDescription: string
	/**
	 * P​ř​i​h​l​á​s​i​t​ ​s​e
	 */
	signIn: string
}

export type Namespaces =
	| 'auth'
	| 'buildLab'
	| 'common'
	| 'home'
	| 'learn'
	| 'library'
	| 'nav'
	| 'practice'
	| 'radar'
	| 'userMenu'

type DisallowNamespaces = {
	/**
	 * reserved for 'auth'-namespace\
	 * you need to use the `./auth/index.ts` file instead
	 */
	auth?: "[typesafe-i18n] reserved for 'auth'-namespace. You need to use the `./auth/index.ts` file instead."

	/**
	 * reserved for 'buildLab'-namespace\
	 * you need to use the `./buildLab/index.ts` file instead
	 */
	buildLab?: "[typesafe-i18n] reserved for 'buildLab'-namespace. You need to use the `./buildLab/index.ts` file instead."

	/**
	 * reserved for 'common'-namespace\
	 * you need to use the `./common/index.ts` file instead
	 */
	common?: "[typesafe-i18n] reserved for 'common'-namespace. You need to use the `./common/index.ts` file instead."

	/**
	 * reserved for 'home'-namespace\
	 * you need to use the `./home/index.ts` file instead
	 */
	home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead."

	/**
	 * reserved for 'learn'-namespace\
	 * you need to use the `./learn/index.ts` file instead
	 */
	learn?: "[typesafe-i18n] reserved for 'learn'-namespace. You need to use the `./learn/index.ts` file instead."

	/**
	 * reserved for 'library'-namespace\
	 * you need to use the `./library/index.ts` file instead
	 */
	library?: "[typesafe-i18n] reserved for 'library'-namespace. You need to use the `./library/index.ts` file instead."

	/**
	 * reserved for 'nav'-namespace\
	 * you need to use the `./nav/index.ts` file instead
	 */
	nav?: "[typesafe-i18n] reserved for 'nav'-namespace. You need to use the `./nav/index.ts` file instead."

	/**
	 * reserved for 'practice'-namespace\
	 * you need to use the `./practice/index.ts` file instead
	 */
	practice?: "[typesafe-i18n] reserved for 'practice'-namespace. You need to use the `./practice/index.ts` file instead."

	/**
	 * reserved for 'radar'-namespace\
	 * you need to use the `./radar/index.ts` file instead
	 */
	radar?: "[typesafe-i18n] reserved for 'radar'-namespace. You need to use the `./radar/index.ts` file instead."

	/**
	 * reserved for 'userMenu'-namespace\
	 * you need to use the `./userMenu/index.ts` file instead
	 */
	userMenu?: "[typesafe-i18n] reserved for 'userMenu'-namespace. You need to use the `./userMenu/index.ts` file instead."
}

export type TranslationFunctions = {
	auth: {
		/**
		 * Přihlášení
		 */
		signInTitle: () => LocalizedString
		/**
		 * Použijte svůj pracovní Google účet nebo si nechte poslat jednorázový odkaz na e-mail.
		 */
		signInDescription: () => LocalizedString
		/**
		 * Pokračovat přes Google
		 */
		continueWithGoogle: () => LocalizedString
		/**
		 * nebo
		 */
		orDivider: () => LocalizedString
		/**
		 * vy@firma.cz
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Poslat odkaz na e-mail
		 */
		sendMagicLink: () => LocalizedString
		/**
		 * Zkontrolujte schránku
		 */
		magicLinkSentTitle: () => LocalizedString
		/**
		 * Odkaz jsme poslali na {email}. Klikněte na něj pro dokončení přihlášení.
		 */
		magicLinkSentBody: (arg: { email: unknown }) => LocalizedString
		/**
		 * Odkaz odeslán — zkontrolujte schránku.
		 */
		magicLinkSentToast: () => LocalizedString
		/**
		 * Přihlášení přes Google se nezdařilo
		 */
		googleSignInFailed: () => LocalizedString
		/**
		 * Přihlášení e-mailem se nezdařilo
		 */
		emailSignInFailed: () => LocalizedString
		/**
		 * Přihlášením souhlasíte s interními pravidly používání.
		 */
		terms: () => LocalizedString
		/**
		 * Dokončuji přihlášení…
		 */
		finishingSignIn: () => LocalizedString
	}
	buildLab: {
		/**
		 * Build Lab
		 */
		eyebrow: () => LocalizedString
		/**
		 * Stavební prvky pro AI
		 */
		title: () => LocalizedString
		/**
		 * Prompty pro Cursor, playbooky pro chatboty, šablony a kontrolní seznamy.
		 */
		description: () => LocalizedString
		/**
		 * Tato kategorie je prázdná
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Brzy sem přidáme další obsah.
		 */
		emptyDescription: () => LocalizedString
	}
	common: {
		/**
		 * AI Academy
		 */
		appName: () => LocalizedString
		/**
		 * interní · MVP
		 */
		tagline: () => LocalizedString
		/**
		 * Načítání…
		 */
		loading: () => LocalizedString
		/**
		 * Něco se pokazilo
		 */
		error: () => LocalizedString
		/**
		 * Zkusit znovu
		 */
		retry: () => LocalizedString
		/**
		 * Uložit
		 */
		save: () => LocalizedString
		/**
		 * Zrušit
		 */
		cancel: () => LocalizedString
		/**
		 * Zavřít
		 */
		close: () => LocalizedString
		/**
		 * Hledat
		 */
		search: () => LocalizedString
		/**
		 * Kopírovat
		 */
		copy: () => LocalizedString
		/**
		 * Zkopírováno
		 */
		copied: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		signIn: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		signOut: () => LocalizedString
		/**
		 * {count|num} min
		 */
		minutesShort: (arg: { count: unknown }) => LocalizedString
		/**
		 * ~{count|num} min
		 */
		estimatedReadingShort: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count|num} {{téma|témata|témat}}
		 */
		countTopics: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * {count|num} {{otázka|otázky|otázek}}
		 */
		countQuestions: (arg: { count: string | number | boolean }) => LocalizedString
	}
	home: {
		/**
		 * Vítejte
		 */
		eyebrow: () => LocalizedString
		/**
		 * AI Academy
		 */
		title: () => LocalizedString
		/**
		 * Malé interní hřiště pro to, jak se v AI zlepšit — společně. Vyberte si sekci nebo se podívejte, co tento týden vyšlo.
		 */
		description: () => LocalizedString
		/**
		 * Začít se učit
		 */
		startLearning: () => LocalizedString
		/**
		 * Otevřít Radar
		 */
		openRadar: () => LocalizedString
		/**
		 * Sekce
		 */
		sectionsHeading: () => LocalizedString
		/**
		 * Nejnovější témata
		 */
		latestTopics: () => LocalizedString
		/**
		 * Procházet vše
		 */
		browseAll: () => LocalizedString
		/**
		 * Z Radaru
		 */
		fromTheRadar: () => LocalizedString
	}
	learn: {
		/**
		 * Učení
		 */
		eyebrow: () => LocalizedString
		/**
		 * Mapa AI učení
		 */
		title: () => LocalizedString
		/**
		 * Krátká, vyhraněná cesta tématy, ve kterých by se měl orientovat každý interní tým. Vyberte si trasu nebo skočte rovnou do libovolného tématu.
		 */
		description: () => LocalizedString
		/**
		 * Trasy
		 */
		statTracks: () => LocalizedString
		/**
		 * Témata
		 */
		statTopics: () => LocalizedString
		/**
		 * Odhadované čtení
		 */
		statEstimatedReading: () => LocalizedString
		/**
		 * Trasa
		 */
		trackEyebrow: () => LocalizedString
		/**
		 * odvozeno
		 */
		trackDerived: () => LocalizedString
		/**
		 * {count|num} {{téma|témata|témat}}
		 */
		topicsCount: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Nezařazená témata
		 */
		uncategorisedTitle: () => LocalizedString
		/**
		 * Témata, která zatím nejsou napojena na žádnou trasu.
		 */
		uncategorisedDescription: () => LocalizedString
		/**
		 * Trasa {n|num}
		 */
		derivedTrackTitle: (arg: { n: unknown }) => LocalizedString
		/**
		 * Metadata trasy nejsou k dispozici — zobrazují se témata podle uloženého ID trasy.
		 */
		derivedTrackDescription: () => LocalizedString
		/**
		 * Otevřít téma
		 */
		openTopic: () => LocalizedString
		/**
		 * {count|num} min
		 */
		topicMinutes: (arg: { count: unknown }) => LocalizedString
	}
	library: {
		/**
		 * Knihovna
		 */
		eyebrow: () => LocalizedString
		/**
		 * Vaše uložené zdroje a poznámky
		 */
		title: () => LocalizedString
		/**
		 * Vše, co jste si uložili z Radaru a Učení, plus vaše osobní poznámky.
		 */
		description: () => LocalizedString
		/**
		 * Uložené
		 */
		tabSaved: () => LocalizedString
		/**
		 * Poznámky
		 */
		tabNotes: () => LocalizedString
		/**
		 * Knihovna je zatím prázdná
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Uložte si zdroje z Radaru nebo Učení — najdete je tady.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Zatím žádné poznámky
		 */
		notesEmptyTitle: () => LocalizedString
		/**
		 * Vytvořte si poznámku k tématu nebo zdroji.
		 */
		notesEmptyDescription: () => LocalizedString
	}
	nav: {
		/**
		 * Domů
		 */
		homeLink: () => LocalizedString
		/**
		 * Učení
		 */
		learnLink: () => LocalizedString
		/**
		 * Radar
		 */
		radarLink: () => LocalizedString
		/**
		 * Knihovna
		 */
		libraryLink: () => LocalizedString
		/**
		 * Procvičování
		 */
		practiceLink: () => LocalizedString
		/**
		 * Build Lab
		 */
		buildLabLink: () => LocalizedString
		/**
		 * Rozbalit panel
		 */
		expandSidebar: () => LocalizedString
		/**
		 * Sbalit panel
		 */
		collapseSidebar: () => LocalizedString
	}
	practice: {
		/**
		 * Procvičování
		 */
		eyebrow: () => LocalizedString
		/**
		 * Kvízy a kartičky
		 */
		title: () => LocalizedString
		/**
		 * Krátké kvízy generované z témat. Začněte předpřipraveným kvízem nebo si nechte vygenerovat nový.
		 */
		description: () => LocalizedString
		/**
		 * Spustit kvíz
		 */
		startQuiz: () => LocalizedString
		/**
		 * Zatím žádné kvízy
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Tématům zatím nebyly přiřazeny žádné kvízy.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Procvičování s AI
		 */
		aiCardTitle: () => LocalizedString
		/**
		 * Vygenerujte nové otázky k tomuto tématu na vyžádání.
		 */
		aiCardDescription: () => LocalizedString
		/**
		 * Generovat
		 */
		generate: () => LocalizedString
		/**
		 * Vygenerovat znovu
		 */
		regenerate: () => LocalizedString
		/**
		 * Generuji…
		 */
		generating: () => LocalizedString
		/**
		 * Generování selhalo
		 */
		generationFailed: () => LocalizedString
		/**
		 * Vygenerováno {count|num} {{otázka|otázky|otázek}}
		 */
		generatedToast: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Otázka {n|num}
		 */
		questionLabel: (arg: { n: unknown }) => LocalizedString
		/**
		 * Výběr
		 */
		questionKindMcq: () => LocalizedString
		/**
		 * Kartička
		 */
		questionKindFlashcard: () => LocalizedString
		/**
		 * Odpověď:
		 */
		answerLabel: () => LocalizedString
	}
	radar: {
		/**
		 * Radar
		 */
		eyebrow: () => LocalizedString
		/**
		 * Co je nového v AI
		 */
		title: () => LocalizedString
		/**
		 * Souhrn článků, novinek a vědeckých prací z našich důvěryhodných zdrojů.
		 */
		description: () => LocalizedString
		/**
		 * Zatím nic nového
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Až dorazí čerstvé položky, objeví se zde.
		 */
		emptyDescription: () => LocalizedString
	}
	userMenu: {
		/**
		 * Nabídka uživatele
		 */
		trigger: () => LocalizedString
		/**
		 * Vzhled
		 */
		appearance: () => LocalizedString
		/**
		 * Motiv
		 */
		theme: () => LocalizedString
		/**
		 * Světlý
		 */
		themeLight: () => LocalizedString
		/**
		 * Tmavý
		 */
		themeDark: () => LocalizedString
		/**
		 * Systém
		 */
		themeSystem: () => LocalizedString
		/**
		 * Jazyk
		 */
		language: () => LocalizedString
		/**
		 * Kopírovat e-mail
		 */
		copyEmail: () => LocalizedString
		/**
		 * E-mail zkopírován
		 */
		copiedEmail: () => LocalizedString
		/**
		 * E-mail se nepodařilo zkopírovat
		 */
		copyEmailFailed: () => LocalizedString
		/**
		 * Klávesové zkratky
		 */
		keyboardShortcuts: () => LocalizedString
		/**
		 * Klávesové zkratky brzy
		 */
		keyboardShortcutsToast: () => LocalizedString
		/**
		 * Po zprovoznění bude „/“ zaměřovat vyhledávání.
		 */
		keyboardShortcutsHint: () => LocalizedString
		/**
		 * Odhlásit se
		 */
		signOut: () => LocalizedString
		/**
		 * Odhlášeno
		 */
		signedOut: () => LocalizedString
		/**
		 * Odhlášení selhalo
		 */
		signOutFailed: () => LocalizedString
		/**
		 * Demo režim
		 */
		demoModeTitle: () => LocalizedString
		/**
		 * Pro přihlášení nakonfigurujte Supabase.
		 */
		demoModeDescription: () => LocalizedString
		/**
		 * Přihlásit se
		 */
		signIn: () => LocalizedString
	}
}

export type Formatters = {
	num: (value: unknown | string | number | boolean) => unknown
}
