// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Namespaces, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslationLoaders = {
	cs: () => import('./cs'),
	en: () => import('./en'),
	pl: () => import('./pl'),
	sk: () => import('./sk'),
}

const localeNamespaceLoaders = {
	cs: {
		auth: () => import('./cs/auth'),
		buildLab: () => import('./cs/buildLab'),
		common: () => import('./cs/common'),
		content: () => import('./cs/content'),
		home: () => import('./cs/home'),
		learn: () => import('./cs/learn'),
		library: () => import('./cs/library'),
		nav: () => import('./cs/nav'),
		paperSearch: () => import('./cs/paperSearch'),
		practice: () => import('./cs/practice'),
		radar: () => import('./cs/radar'),
		reader: () => import('./cs/reader'),
		userMenu: () => import('./cs/userMenu')
	},
	en: {
		auth: () => import('./en/auth'),
		buildLab: () => import('./en/buildLab'),
		common: () => import('./en/common'),
		content: () => import('./en/content'),
		home: () => import('./en/home'),
		learn: () => import('./en/learn'),
		library: () => import('./en/library'),
		nav: () => import('./en/nav'),
		paperSearch: () => import('./en/paperSearch'),
		practice: () => import('./en/practice'),
		radar: () => import('./en/radar'),
		reader: () => import('./en/reader'),
		userMenu: () => import('./en/userMenu')
	},
	pl: {
		auth: () => import('./pl/auth'),
		buildLab: () => import('./pl/buildLab'),
		common: () => import('./pl/common'),
		content: () => import('./pl/content'),
		home: () => import('./pl/home'),
		learn: () => import('./pl/learn'),
		library: () => import('./pl/library'),
		nav: () => import('./pl/nav'),
		paperSearch: () => import('./pl/paperSearch'),
		practice: () => import('./pl/practice'),
		radar: () => import('./pl/radar'),
		reader: () => import('./pl/reader'),
		userMenu: () => import('./pl/userMenu')
	},
	sk: {
		auth: () => import('./sk/auth'),
		buildLab: () => import('./sk/buildLab'),
		common: () => import('./sk/common'),
		content: () => import('./sk/content'),
		home: () => import('./sk/home'),
		learn: () => import('./sk/learn'),
		library: () => import('./sk/library'),
		nav: () => import('./sk/nav'),
		paperSearch: () => import('./sk/paperSearch'),
		practice: () => import('./sk/practice'),
		radar: () => import('./sk/radar'),
		reader: () => import('./sk/reader'),
		userMenu: () => import('./sk/userMenu')
	}
}

const updateDictionary = (locale: Locales, dictionary: Partial<Translations>): Translations =>
	loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }

export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
	(await localeTranslationLoaders[locale]()).default as unknown as Translations

export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
	updateDictionary(locale, await importLocaleAsync(locale))
	loadFormatters(locale)
}

export const loadAllLocalesAsync = (): Promise<void[]> => Promise.all(locales.map(loadLocaleAsync))

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))

export const importNamespaceAsync = async<Namespace extends Namespaces>(locale: Locales, namespace: Namespace) =>
	(await localeNamespaceLoaders[locale][namespace]()).default as unknown as Translations[Namespace]

export const loadNamespaceAsync = async <Namespace extends Namespaces>(locale: Locales, namespace: Namespace): Promise<void> =>
	void updateDictionary(locale, { [namespace]: await importNamespaceAsync(locale, namespace )})
