// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import cs from './cs'
import en from './en'
import pl from './pl'
import sk from './sk'

import cs_auth from './cs/auth'
import cs_buildLab from './cs/buildLab'
import cs_common from './cs/common'
import cs_content from './cs/content'
import cs_home from './cs/home'
import cs_learn from './cs/learn'
import cs_library from './cs/library'
import cs_nav from './cs/nav'
import cs_paperSearch from './cs/paperSearch'
import cs_practice from './cs/practice'
import cs_radar from './cs/radar'
import cs_reader from './cs/reader'
import cs_userMenu from './cs/userMenu'
import en_auth from './en/auth'
import en_buildLab from './en/buildLab'
import en_common from './en/common'
import en_content from './en/content'
import en_home from './en/home'
import en_learn from './en/learn'
import en_library from './en/library'
import en_nav from './en/nav'
import en_paperSearch from './en/paperSearch'
import en_practice from './en/practice'
import en_radar from './en/radar'
import en_reader from './en/reader'
import en_userMenu from './en/userMenu'
import pl_auth from './pl/auth'
import pl_buildLab from './pl/buildLab'
import pl_common from './pl/common'
import pl_content from './pl/content'
import pl_home from './pl/home'
import pl_learn from './pl/learn'
import pl_library from './pl/library'
import pl_nav from './pl/nav'
import pl_paperSearch from './pl/paperSearch'
import pl_practice from './pl/practice'
import pl_radar from './pl/radar'
import pl_reader from './pl/reader'
import pl_userMenu from './pl/userMenu'
import sk_auth from './sk/auth'
import sk_buildLab from './sk/buildLab'
import sk_common from './sk/common'
import sk_content from './sk/content'
import sk_home from './sk/home'
import sk_learn from './sk/learn'
import sk_library from './sk/library'
import sk_nav from './sk/nav'
import sk_paperSearch from './sk/paperSearch'
import sk_practice from './sk/practice'
import sk_radar from './sk/radar'
import sk_reader from './sk/reader'
import sk_userMenu from './sk/userMenu'

const localeTranslations = {
	cs: {
		...cs,
		auth: cs_auth,
		buildLab: cs_buildLab,
		common: cs_common,
		content: cs_content,
		home: cs_home,
		learn: cs_learn,
		library: cs_library,
		nav: cs_nav,
		paperSearch: cs_paperSearch,
		practice: cs_practice,
		radar: cs_radar,
		reader: cs_reader,
		userMenu: cs_userMenu
	},
	en: {
		...en,
		auth: en_auth,
		buildLab: en_buildLab,
		common: en_common,
		content: en_content,
		home: en_home,
		learn: en_learn,
		library: en_library,
		nav: en_nav,
		paperSearch: en_paperSearch,
		practice: en_practice,
		radar: en_radar,
		reader: en_reader,
		userMenu: en_userMenu
	},
	pl: {
		...pl,
		auth: pl_auth,
		buildLab: pl_buildLab,
		common: pl_common,
		content: pl_content,
		home: pl_home,
		learn: pl_learn,
		library: pl_library,
		nav: pl_nav,
		paperSearch: pl_paperSearch,
		practice: pl_practice,
		radar: pl_radar,
		reader: pl_reader,
		userMenu: pl_userMenu
	},
	sk: {
		...sk,
		auth: sk_auth,
		buildLab: sk_buildLab,
		common: sk_common,
		content: sk_content,
		home: sk_home,
		learn: sk_learn,
		library: sk_library,
		nav: sk_nav,
		paperSearch: sk_paperSearch,
		practice: sk_practice,
		radar: sk_radar,
		reader: sk_reader,
		userMenu: sk_userMenu
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
