-- Seed: canonical / foundational AI papers, surfaced via /library/canon.
--
-- Stored as regular `resources` rows so they reuse the Library Save flow,
-- embeddings column, content-key localization, etc. The `is_canonical = true`
-- flag plus `canonical_category` is the only thing that distinguishes them.
--
-- Title/summary use stable translation keys under `content.canon.*`, with
-- Czech text in the base columns as a fallback.

insert into public.resources (
  url, title, title_key, source_name, kind, summary, summary_key,
  author, published_at, tags, enrichment_status,
  external_id, is_canonical, canonical_category, canonical_position
) values
  -- Foundations
  ('https://arxiv.org/abs/1706.03762',
   'Attention Is All You Need',
   'content.canon.attentionIsAllYouNeed.title',
   'arXiv', 'paper',
   'Původní článek představující architekturu Transformer. Základ moderních LLM.',
   'content.canon.attentionIsAllYouNeed.summary',
   'Vaswani et al.', '2017-06-12T00:00:00Z',
   '{"transformer","foundations","attention"}', 'manual',
   'arXiv:1706.03762', true, 'foundations', 1),
  ('https://arxiv.org/abs/2001.08361',
   'Škálovací zákony pro jazykové modely',
   'content.canon.scalingLaws.title',
   'arXiv', 'paper',
   'OpenAI scaling laws: jak roste výkon modelu s velikostí dat, parametrů a výpočtu.',
   'content.canon.scalingLaws.summary',
   'Kaplan et al.', '2020-01-23T00:00:00Z',
   '{"scaling","openai","foundations"}', 'manual',
   'arXiv:2001.08361', true, 'foundations', 2),
  ('https://arxiv.org/abs/2203.15556',
   'Chinchilla: výpočetně optimální trénink LLM',
   'content.canon.chinchilla.title',
   'arXiv', 'paper',
   'DeepMind ukazuje, že většina LLM byla podtrénovaná na datech vůči svému výpočtu.',
   'content.canon.chinchilla.summary',
   'Hoffmann et al.', '2022-03-29T00:00:00Z',
   '{"scaling","deepmind","training"}', 'manual',
   'arXiv:2203.15556', true, 'foundations', 3),

  -- Models
  ('https://arxiv.org/abs/1810.04805',
   'BERT: hluboké obousměrné transformery pro porozumění jazyku',
   'content.canon.bert.title',
   'arXiv', 'paper',
   'Encoder-only model, který popularizoval pre-training / fine-tuning paradigma.',
   'content.canon.bert.summary',
   'Devlin et al.', '2018-10-11T00:00:00Z',
   '{"bert","encoder","pretraining"}', 'manual',
   'arXiv:1810.04805', true, 'models', 1),
  ('https://arxiv.org/abs/2005.14165',
   'GPT-3: jazykové modely jsou few-shot learnery',
   'content.canon.gpt3.title',
   'arXiv', 'paper',
   'Článek, který ukázal, že škálování + in-context learning vede k emergentním schopnostem.',
   'content.canon.gpt3.summary',
   'Brown et al.', '2020-05-28T00:00:00Z',
   '{"gpt-3","openai","in-context-learning"}', 'manual',
   'arXiv:2005.14165', true, 'models', 2),
  ('https://arxiv.org/abs/2302.13971',
   'LLaMA: efektivní základní jazykové modely',
   'content.canon.llama.title',
   'arXiv', 'paper',
   'Meta uvolňuje silnou rodinu otevřených modelů a odstartuje open-source LLM ekosystém.',
   'content.canon.llama.summary',
   'Touvron et al.', '2023-02-27T00:00:00Z',
   '{"llama","meta","open-source"}', 'manual',
   'arXiv:2302.13971', true, 'models', 3),
  ('https://arxiv.org/abs/2401.04088',
   'Mixtral of Experts',
   'content.canon.mixtral.title',
   'arXiv', 'paper',
   'Mistral popisuje sparse mixture-of-experts model 8x7B s GPT-3.5 výkonem za zlomek nákladů.',
   'content.canon.mixtral.summary',
   'Jiang et al.', '2024-01-08T00:00:00Z',
   '{"mixtral","mistral","moe"}', 'manual',
   'arXiv:2401.04088', true, 'models', 4),

  -- Alignment / RLHF
  ('https://arxiv.org/abs/2203.02155',
   'InstructGPT: trénink LLM podle lidských preferencí',
   'content.canon.instructgpt.title',
   'arXiv', 'paper',
   'Článek za ChatGPT: RLHF, který naučil GPT-3 plnit instrukce.',
   'content.canon.instructgpt.summary',
   'Ouyang et al.', '2022-03-04T00:00:00Z',
   '{"rlhf","alignment","openai"}', 'manual',
   'arXiv:2203.02155', true, 'alignment', 1),
  ('https://arxiv.org/abs/2212.08073',
   'Constitutional AI: bezpečnost přes AI feedback',
   'content.canon.constitutionalAi.title',
   'arXiv', 'paper',
   'Anthropic ukazuje RLAIF: AI hodnotí výstupy podle psaného souboru principů.',
   'content.canon.constitutionalAi.summary',
   'Bai et al.', '2022-12-15T00:00:00Z',
   '{"alignment","anthropic","rlaif"}', 'manual',
   'arXiv:2212.08073', true, 'alignment', 2),
  ('https://arxiv.org/abs/2305.18290',
   'DPO: přímá optimalizace preferencí',
   'content.canon.dpo.title',
   'arXiv', 'paper',
   'Trénink LLM podle preferenčních párů bez explicitního reward modelu — jednodušší než RLHF.',
   'content.canon.dpo.summary',
   'Rafailov et al.', '2023-05-29T00:00:00Z',
   '{"dpo","alignment","preference"}', 'manual',
   'arXiv:2305.18290', true, 'alignment', 3),

  -- Prompting & reasoning
  ('https://arxiv.org/abs/2201.11903',
   'Chain-of-Thought Prompting',
   'content.canon.cot.title',
   'arXiv', 'paper',
   'Ukazuje, jak prompty s mezikroky úvah zlepšují vícekrokové uvažování LLM.',
   'content.canon.cot.summary',
   'Wei et al.', '2022-01-28T00:00:00Z',
   '{"prompting","reasoning","cot"}', 'manual',
   'arXiv:2201.11903', true, 'prompting', 1),

  -- Agents & tools
  ('https://arxiv.org/abs/2210.03629',
   'ReAct: propojení uvažování a jednání',
   'content.canon.react.title',
   'arXiv', 'paper',
   'Klasický agentní vzor: jazykový model střídá kroky uvažování a volání nástrojů.',
   'content.canon.react.summary',
   'Yao et al.', '2022-10-06T00:00:00Z',
   '{"agents","react","tools"}', 'manual',
   'arXiv:2210.03629', true, 'agents', 1),
  ('https://arxiv.org/abs/2302.04761',
   'Toolformer: jazykové modely se učí používat nástroje',
   'content.canon.toolformer.title',
   'arXiv', 'paper',
   'Meta ukazuje, jak LLM samostatně získá schopnost volat externí API.',
   'content.canon.toolformer.summary',
   'Schick et al.', '2023-02-09T00:00:00Z',
   '{"tools","agents","meta"}', 'manual',
   'arXiv:2302.04761', true, 'agents', 2),

  -- RAG
  ('https://arxiv.org/abs/2005.11401',
   'Retrieval-Augmented Generation pro NLP',
   'content.canon.rag.title',
   'arXiv', 'paper',
   'Původní článek RAG: kombinace retrieve + generate pro úlohy nad znalostmi.',
   'content.canon.rag.summary',
   'Lewis et al.', '2020-05-22T00:00:00Z',
   '{"rag","retrieval","nlp"}', 'manual',
   'arXiv:2005.11401', true, 'rag', 1)
on conflict (url) do update
  set title = excluded.title,
      title_key = excluded.title_key,
      summary = excluded.summary,
      summary_key = excluded.summary_key,
      source_name = excluded.source_name,
      kind = excluded.kind,
      author = excluded.author,
      published_at = excluded.published_at,
      tags = excluded.tags,
      external_id = excluded.external_id,
      is_canonical = excluded.is_canonical,
      canonical_category = excluded.canonical_category,
      canonical_position = excluded.canonical_position,
      enrichment_status = excluded.enrichment_status;
